### ISSUE TITLE
Add myself to a dialog created by other user

### ISSUE THREAD

**Issue by khawarraza** [QuickBlox/quickblox-android-sdk#237]
I am using 2.5.1 of QuickBlox in Android. I am having trouble figuring out the way I should lay down my app logic. In my app, users create events and other users join this event. I want to create a chat dialog when event is created and when a user joins the event, I want to add that user to the dialog. I have read the docs that only dialog owner can update the dialog. I have seen public group dialog but creating public dialog means every user can see this dialog which go against my app logic. So can you suggest me some workaround for this so that when a user joins event, it gets added into the dialog? thanks!

**Comment by Hemant0601** [comment]
@khawarraza As the limitation is what you are aware about, so a workaround could be as follows:
Step 1: detect when user wants to join the group
Step 2: send a private message to the owner of the group. the message should have a save_to_history flag set to 0 so that the owner wont notice it. 
Step 3: once it is received by owner add your code to add user to group
Step 4: send a message from the owner saying User1 added to the group(your choice to make it visible or not so keep flag save_to_history acc to your requirement)

P.S there may be the case that u send a addtogroup request once, so add it in some periodic scheme untill u find that groupDialog.getOccupants() have your userId in it.

Cheers :)

**Comment by khawarraza** [comment]
That way the joiner would have to wait for the group creator to become online, receive message and add him to group in background. And what if this message get missed/lost somehow? There should have been some way like calling API methods with some master key or admin access from anywhere to do such things. Is there any?

**Comment by vfite** [comment]
@khawarraza You've already mentioned that in your app users create events. So you just need channel which will be notify users of event. In this case you can use Push notifications - http://quickblox.com/developers/SimpleSample-messages_users-android, which perform any notifications.
Or as @Hemant0601 said you can use chat to notify users and trigger your logic.

**Comment by tatanka987** [comment]
Close. long time inactivity
