### ISSUE TITLE
java.lang.ClassNotFoundException : "org.webrtc.CameraEnumerator" while startcall

### ISSUE THREAD

**Issue by qw99992** [QuickBlox/quickblox-android-sdk#287]
09-14 14:46:43.191: W/System.err(6887): java.lang.ClassNotFoundException: Didn't find class "org.webrtc.CameraEnumerator" on path: DexPathList[[zip file "/data/app/com.example.rtctest-1/base.apk"],nativeLibraryDirectories=[/data/app/com.example.rtctest-1/lib/arm, /system/lib, /vendor/lib, system/vendor/lib, system/vendor/lib/egl, system/lib/hw]]
09-14 14:46:43.191: W/System.err(6887): 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
09-14 14:46:43.191: W/System.err(6887): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
09-14 14:46:43.191: W/System.err(6887): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
09-14 14:46:43.191: W/System.err(6887): 	at java.lang.Runtime.nativeLoad(Native Method)
09-14 14:46:43.191: W/System.err(6887): 	at java.lang.Runtime.doLoad(Runtime.java:428)
09-14 14:46:43.191: W/System.err(6887): 	at java.lang.Runtime.loadLibrary(Runtime.java:369)
09-14 14:46:43.191: W/System.err(6887): 	at java.lang.System.loadLibrary(System.java:989)
09-14 14:46:43.191: W/System.err(6887): 	at org.webrtc.PeerConnectionFactory.<clinit>(PeerConnectionFactory.java:39)
09-14 14:46:43.191: W/System.err(6887): 	at com.quickblox.videochat.webrtc.PeerFactoryManager.initializeFactoryFieldTrials(PeerFactoryManager.java:109)
09-14 14:46:43.191: W/System.err(6887): 	at com.quickblox.videochat.webrtc.PeerFactoryManager.initPeerConnectionFactory(PeerFactoryManager.java:83)
09-14 14:46:43.191: W/System.err(6887): 	at com.quickblox.videochat.webrtc.PeerFactoryManager.access$100(PeerFactoryManager.java:11)
09-14 14:46:43.191: W/System.err(6887): 	at com.quickblox.videochat.webrtc.PeerFactoryManager$1.run(PeerFactoryManager.java:59)
09-14 14:46:43.191: W/System.err(6887): 	at android.os.Handler.handleCallback(Handler.java:739)
09-14 14:46:43.191: W/System.err(6887): 	at android.os.Handler.dispatchMessage(Handler.java:95)
09-14 14:46:43.191: W/System.err(6887): 	at android.os.Looper.loop(Looper.java:155)
09-14 14:46:43.191: W/System.err(6887): 	at com.quickblox.videochat.webrtc.LooperExecutor.run(LooperExecutor.java:74)
09-14 14:46:43.191: W/System.err(6887): 	Suppressed: java.lang.ClassNotFoundException: org.webrtc.CameraEnumerator
09-14 14:46:43.191: W/System.err(6887): 		at java.lang.Class.classForName(Native Method)
09-14 14:46:43.191: W/System.err(6887): 		at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
09-14 14:46:43.191: W/System.err(6887): 		at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
09-14 14:46:43.191: W/System.err(6887): 		at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
09-14 14:46:43.191: W/System.err(6887): 		... 14 more
09-14 14:46:43.191: W/System.err(6887): 	Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack available
09-14 14:46:43.191: E/rtc(6887): #
09-14 14:46:43.191: E/rtc(6887): # Fatal error in ../../webrtc/api/java/jni/classreferenceholder.cc, line 122
09-14 14:46:43.191: E/rtc(6887): # last system error: 2
09-14 14:46:43.191: E/rtc(6887): # Check failed: !jni->ExceptionCheck()
09-14 14:46:43.191: E/rtc(6887): # error during FindClass: org/webrtc/CameraEnumerator
09-14 14:46:43.191: E/rtc(6887): #
09-14 14:46:43.191: A/libc(6887): Fatal signal 6 (SIGABRT), code -6 in tid 6942 (Thread-6454)
09-14 14:46:43.191: W/libc(6887): Security Level: (1), Debug inforamtion is controlled by the DUMPABLE flag.

**Comment by tatanka987** [comment]
looks like you didn't update jni libs after update QuickBlox SDK, for do it need move updated .so files from [this link](https://github.com/QuickBlox/quickblox-android-sdk/tree/master/sample-videochat-webrtc/src/main/jniLibs) to your project

**Comment by qw99992** [comment]
thanks a lot.

**Comment by CRUDTechnolgoy** [comment]
i have updated api from 2.4 to 2.6 i have  also update .so file in jniLibs folder but still showing same error to me..  09-24 23:24:47.189 25972-26404/com.ss.fun2sh.Activity W/System.err: java.lang.ClassNotFoundException: Didn't find class "org.webrtc.CameraEnumerator" on path: DexPathList[[dex file "/data/data/com.ss.fun2sh.Activity/files/instant-run/dex/slice-universal-image-loader-1.9.1_c8cce270698544a68b790f538745cec899586791-classes.dex", dex file "/data/data/com.ss.fun2sh.Activity/files/instant-run/dex/slice-support-annotations-24.0.0-beta1_963f476cad816b28cb8abb8161ca5c6c627373dc-classes.dex", dex file "/data/data/com.ss.fun2sh.Activity/files/instant-run/dex/slice-smack-tcp-4.1.6-SNAPSHOT_e0faf8345e88e5905c922cbefcc313aafdc8116f-classes.dex", dex file "/data/data/com.ss.fun2sh.Activity/files/instant-run/dex/slice-smack-sasl-provided-4.1.6-SNAPSHOT_109954fdfcffc76218a142e62fbccbb1cca2ff7d-classes.dex", dex file "/data/data/com.ss.fun2sh.Activity/files/instant-run/dex/slice-smack-resolver-minidns-4.1.6-SNAPSHOT_c110b62180ee1d2bb2ec1bf8c98b851cec158ecf-classes.dex", dex file "/data/data/com.ss.fun2sh.Activity/files/instant-run/dex/slice-smack-im-4.1.6-SNAPSHOT_56c90dfe1237566605acdf10ca4e88447e7a0836-classes.dex", dex file "/data/data/com.ss.fun2sh.Activity/files/instant-run/dex/slice-smack-extensions-4.1.6-SNAPSHOT_2e7146678b81ef0518e8ace41be7645f442c5fde-classes.dex", dex file "/data/data/com.ss.fun2sh.Activity/files/instant-run/dex/slice-smack-experimental-4.1.6-SNAPSHOT_74911960ef64a40dc8b6c52b0a2aa40c173678d7-classes.dex", dex file "/data/data/com.ss.fun2sh.Activity/files/instant-run/dex/slice-smack-core-4.1.6-SNAPSHOT_bb81480c573ee6d13105d773da24263ab7c6133d-classes.dex", dex file "/data/data/com.ss.fun2sh.Activity/files/instant-run/dex/slice-smack-android-4.1.6-SNAPSHOT_11082f0a104319a3f000cc03aa64b38b4a2f8b15-classes.dex", dex file "/data/data/com.ss.fun2sh.Activity/files/instant-run/dex/slice-slice_9-classes.dex", dex file "/data/data/com.ss.fun2sh.Activity/files/instant-run/dex/slice-slice_8-classes.dex", dex file "/data/data/com.ss.fun2sh.Activity/files/instant-run/dex/slice-slice_7-classes.dex", dex file "/data/data/com.ss.fun2sh.Activity/files/instant-run/dex/slice-slice_6-classes.dex", dex file "/data/data/com.ss.fun2sh.Activity/files/instant-run/dex/slice-slice_5-classes.dex", dex file "/data/data/com.ss.fun2sh.Activity/files/instant-run/dex/slice-slice_4-classes.dex", dex file "/data/data/com.ss.fun2sh.Activity/files/instant-run/dex/slice-slice_3-classes.dex", dex file "/data/data/com.ss.fun2sh.Activity/files/instant-run/dex/slice-slice_2-classes.dex", dex file "/data/data/com.ss.fun2sh.Activity/files/instant-run/dex/slice-slice_1-classes.dex", dex file "/data/data/com.ss.fun2sh.Activity/files/instant-run/dex/slice-slice_0-classes.dex", dex file "/data/data/com.ss.fun2sh.Activity/files/instant-run/dex/slice-quickblox-android-sdk-videochat-webrtc-2.6_41eb841a4ea5969bcee600dcd6f2652fecaceaf1-classes.dex", dex file "/data/data/com.ss.fun2sh.Activity/files/instant-run/dex/slice-quickblox-android-sdk-customobjects-2.4_a8cf70d25f139a19a6a872c37d52a046459e3c7a-classes.dex", dex file "/data/data/com.ss.fun2sh.Activity/files/instant-run/dex/slice-qb-gson2.2.1_c6d3c189d4348309a748e591c88ac82366da0dcd-classes.dex", dex file "/data/data/com.ss.fun2sh.Activity/files/instant-run/dex/slice-pl.droidsonroids.gif-android-gif-drawable-1.1.16_fa4f9fc0a851a445165b436227aec56f37ef9847-classes.dex", dex file "/data/data/com.ss.fun2sh.Activity/files/instant-run/dex/slice-picasso-2.3.2_2c464cde9ced0bf3596eaf2a800311c85fcbefa8-classes.dex", dex file "/data/data/com.ss.fun2sh.Activity/files/instant-run/dex/slice-ormlite-core-4.48_e71452b3305b211374fc980f3408329ae8b1b726-classes.dex", dex file "/data/data/com.ss.fun2sh.Activity/files/instant-run/dex/slice-ormlite-android-4.48_7cb5c108964259fc20d63f5e638abf6c6bd45a64-classes.dex", dex file "/data/data/com.ss.fun2sh.Activity/files/instant-run/dex/slice-minidns-0.1.7_6ea93aeca1bd282a10520ff48900e0013190d216-classes.dex", dex file "/data/data/com.ss.fun2sh.Activity/files/instant-run/dex/slice-me.zhanghai.android.materialprogressbar-library-1.1.5_7b7c92c20a05f5fb04e21863ac6632a023940cd6-classes.dex", dex file "/data/data/com.ss.fun2sh.
09-24 23:24:47.190 25972-26404/com.ss.fun2sh.Activity W/System.err:     at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
09-24 23:24:47.190 25972-26404/com.ss.fun2sh.Activity W/System.err:     at com.android.tools.fd.runtime.IncrementalClassLoader$DelegateClassLoader.findClass(IncrementalClassLoader.java:90)
09-24 23:24:47.190 25972-26404/com.ss.fun2sh.Activity W/System.err:     at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
09-24 23:24:47.190 25972-26404/com.ss.fun2sh.Activity W/System.err:     at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
09-24 23:24:47.190 25972-26404/com.ss.fun2sh.Activity W/System.err:     at java.lang.Runtime.nativeLoad(Native Method)
09-24 23:24:47.190 25972-26404/com.ss.fun2sh.Activity W/System.err:     at java.lang.Runtime.doLoad(Runtime.java:428)
09-24 23:24:47.190 25972-26404/com.ss.fun2sh.Activity W/System.err:     at java.lang.Runtime.loadLibrary(Runtime.java:369)
09-24 23:24:47.190 25972-26404/com.ss.fun2sh.Activity W/System.err:     at java.lang.System.loadLibrary(System.java:988)
09-24 23:24:47.190 25972-26404/com.ss.fun2sh.Activity W/System.err:     at org.webrtc.PeerConnectionFactory.<clinit>(PeerConnectionFactory.java:39)
09-24 23:24:47.190 25972-26404/com.ss.fun2sh.Activity W/System.err:     at com.quickblox.videochat.webrtc.PeerFactoryManager.initializeFactoryFieldTrials(PeerFactoryManager.java:109)
09-24 23:24:47.190 25972-26404/com.ss.fun2sh.Activity W/System.err:     at com.quickblox.videochat.webrtc.PeerFactoryManager.initPeerConnectionFactory(PeerFactoryManager.java:83)
09-24 23:24:47.190 25972-26404/com.ss.fun2sh.Activity W/System.err:     at com.quickblox.videochat.webrtc.PeerFactoryManager.access$100(PeerFactoryManager.java:11)
09-24 23:24:47.190 25972-26404/com.ss.fun2sh.Activity W/System.err:     at com.quickblox.videochat.webrtc.PeerFactoryManager$1.run(PeerFactoryManager.java:59)
09-24 23:24:47.190 25972-26404/com.ss.fun2sh.Activity W/System.err:     at android.os.Handler.handleCallback(Handler.java:739)
09-24 23:24:47.190 25972-26404/com.ss.fun2sh.Activity W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:95)
09-24 23:24:47.190 25972-26404/com.ss.fun2sh.Activity W/System.err:     at android.os.Looper.loop(Looper.java:135)
09-24 23:24:47.191 25972-26404/com.ss.fun2sh.Activity W/System.err:     at com.quickblox.videochat.webrtc.LooperExecutor.run(LooperExecutor.java:74)
09-24 23:24:47.191 25972-26404/com.ss.fun2sh.Activity W/System.err: 	Suppressed: java.lang.ClassNotFoundException: Didn't find class "org.webrtc.CameraEnumerator" on path: DexPathList[[zip file "/data/app/com.ss.fun2sh.Activity-1/base.apk"],nativeLibraryDirectories=[/data/app/com.ss.fun2sh.Activity-1/lib/arm64, /vendor/lib64, /system/lib64]]
09-24 23:24:47.191 25972-26404/com.ss.fun2sh.Activity W/System.err:     at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
09-24 23:24:47.191 25972-26404/com.ss.fun2sh.Activity W/System.err:     at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
09-24 23:24:47.191 25972-26404/com.ss.fun2sh.Activity W/System.err:     at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
09-24 23:24:47.191 25972-26404/com.ss.fun2sh.Activity W/System.err: 		... 14 more
09-24 23:24:47.192 25972-26404/com.ss.fun2sh.Activity W/System.err: 		Suppressed: java.lang.ClassNotFoundException: Didn't find class "org.webrtc.CameraEnumerator" on path: DexPathList[[dex file "/data/data/com.ss.fun2sh.Activity/files/instant-run/dex/slice-universal-image-loader-1.9.1_c8cce270698544a68b790f538745cec899586791-classes.dex", dex file "/data/data/com.ss.fun2sh.Activity/files/instant-run/dex/slice-support-annotations-24.0.0-beta1_963f476cad816b28cb8abb8161ca5c6c627373dc-classes.dex", dex file "/data/data/com.ss.fun2sh.Activity/files/instant-run/dex/slice-smack-tcp-4.1.6-SNAPSHOT_e0faf8345e88e5905c922cbefcc313aafdc8116f-classes.dex", dex file "/data/data/com.ss.fun2sh.Activity/files/instant-run/dex/slice-smack-sasl-provided-4.1.6-SNAPSHOT_109954fdfcffc76218a142e62fbccbb1cca2ff7d-classes.dex", dex file "/data/data/com.ss.fun2sh.Activity/files/instant-run/dex/slice-smack-resolver-minidns-4.1.6-SNAPSHOT_c110b62180ee1d2bb2ec1bf8c98b851cec158ecf-classes.dex", dex file "/data/data/com.ss.fun2sh.Activity/files/instant-run/dex/slice-smack-im-4.1.6-SNAPSHOT_56c90dfe1237566605acdf10ca4e88447e7a0836-classes.dex", dex file "/data/data/com.ss.fun2sh.Activity/files/instant-run/dex/slice-smack-extensions-4.1.6-SNAPSHOT_2e7146678b81ef0518e8ace41be7645f442c5fde-classes.dex", dex file "/data/data/com.ss.fun2sh.Activity/files/instant-run/dex/slice-smack-experimental-4.1.6-SNAPSHOT_74911960ef64a40dc8b6c52b0a2aa40c173678d7-classes.dex", dex file "/data/data/com.ss.fun2sh.Activity/files/instant-run/dex/slice-smack-core-4.1.6-SNAPSHOT_bb81480c573ee6d13105d773da24263ab7c6133d-classes.dex", dex file "/data/data/com.ss.fun2sh.Activity/files/instant-run/dex/slice-smack-android-4.1.6-SNAPSHOT_11082f0a104319a3f000cc03aa64b38b4a2f8b15-classes.dex", dex file "/data/data/com.ss.fun2sh.Activity/files/instant-run/dex/slice-slice_9-classes.dex", dex file "/data/data/com.ss.fun2sh.Activity/files/instant-run/dex/slice-slice_8-classes.dex", dex file "/data/data/com.ss.fun2sh.Activity/files/instant-run/dex/slice-slice_7-classes.dex", dex file "/data/data/com.ss.fun2sh.Activity/files/instant-run/dex/slice-slice_6-classes.dex", dex file "/data/data/com.ss.fun2sh.Activity/files/instant-run/dex/slice-slice_5-classes.dex", dex file "/data/data/com.ss.fun2sh.Activity/files/instant-run/dex/slice-slice_4-classes.dex", dex file "/data/data/com.ss.fun2sh.Activity/files/instant-run/dex/slice-slice_3-classes.dex", dex file "/data/data/com.ss.fun2sh.Activity/files/instant-run/dex/slice-slice_2-classes.dex", dex file "/data/data/com.ss.fun2sh.Activity/files/instant-run/dex/slice-slice_1-classes.dex", dex file "/data/data/com.ss.fun2sh.Activity/files/instant-run/dex/slice-slice_0-classes.dex", dex file "/data/data/com.ss.fun2sh.Activity/files/instant-run/dex/slice-quickblox-android-sdk-videochat-webrtc-2.6_41eb841a4ea5969bcee600dcd6f2652fecaceaf1-classes.dex", dex file "/data/data/com.ss.fun2sh.Activity/files/instant-run/dex/slice-quickblox-android-sdk-customobjects-2.4_a8cf70d25f139a19a6a872c37d52a046459e3c7a-classes.dex", dex file "/data/data/com.ss.fun2sh.Activity/files/instant-run/dex/slice-qb-gson2.2.1_c6d3c189d4348309a748e591c88ac82366da0dcd-classes.dex", dex file "/data/data/com.ss.fun2sh.Activity/files/instant-run/dex/slice-pl.droidsonroids.gif-android-gif-drawable-1.1.16_fa4f9fc0a851a445165b436227aec56f37ef9847-classes.dex", dex file "/data/data/com.ss.fun2sh.Activity/files/instant-run/dex/slice-picasso-2.3.2_2c464cde9ced0bf3596eaf2a800311c85fcbefa8-classes.dex", dex file "/data/data/com.ss.fun2sh.Activity/files/instant-run/dex/slice-ormlite-core-4.48_e71452b3305b211374fc980f3408329ae8b1b726-classes.dex", dex file "/data/data/com.ss.fun2sh.Activity/files/instant-run/dex/slice-ormlite-android-4.48_7cb5c108964259fc20d63f5e638abf6c6bd45a64-classes.dex", dex file "/data/data/com.ss.fun2sh.Activity/files/instant-run/dex/slice-minidns-0.1.7_6ea93aeca1bd282a10520ff48900e0013190d216-classes.dex", dex file "/data/data/com.ss.fun2sh.Activity/files/instant-run/dex/slice-me.zhanghai.android.materialprogressbar-library-1.1.5_7b7c92c20a05f5fb04e21863ac6632a023940cd6-classes.dex", dex file "/data/data/
09-24 23:24:47.193 25972-26404/com.ss.fun2sh.Activity W/System.err:     at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
09-24 23:24:47.193 25972-26404/com.ss.fun2sh.Activity W/System.err:     at com.android.tools.fd.runtime.IncrementalClassLoader$DelegateClassLoader.findClass(IncrementalClassLoader.java:90)
09-24 23:24:47.193 25972-26404/com.ss.fun2sh.Activity W/System.err:     at com.android.tools.fd.runtime.IncrementalClassLoader.findClass(IncrementalClassLoader.java:62)
09-24 23:24:47.193 25972-26404/com.ss.fun2sh.Activity W/System.err:     at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
09-24 23:24:47.193 25972-26404/com.ss.fun2sh.Activity W/System.err:     at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
09-24 23:24:47.193 25972-26404/com.ss.fun2sh.Activity W/System.err: 			... 15 more
09-24 23:24:47.193 25972-26404/com.ss.fun2sh.Activity W/System.err: 			Suppressed: java.lang.ClassNotFoundException: org.webrtc.CameraEnumerator
09-24 23:24:47.194 25972-26404/com.ss.fun2sh.Activity W/System.err:     at java.lang.Class.classForName(Native Method)
09-24 23:24:47.194 25972-26404/com.ss.fun2sh.Activity W/System.err:     at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
09-24 23:24:47.194 25972-26404/com.ss.fun2sh.Activity W/System.err:     at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
09-24 23:24:47.194 25972-26404/com.ss.fun2sh.Activity W/System.err:     at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
09-24 23:24:47.194 25972-26404/com.ss.fun2sh.Activity W/System.err: 				... 16 more
09-24 23:24:47.194 25972-26404/com.ss.fun2sh.Activity W/System.err: 			Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack available
09-24 23:24:47.195 25972-26404/com.ss.fun2sh.Activity E/rtc: #
                                                             # Fatal error in ../../webrtc/api/java/jni/classreferenceholder.cc, line 122
                                                             # last system error: 2
                                                             # Check failed: !jni->ExceptionCheck()
                                                             # error during FindClass: org/webrtc/CameraEnumerator
                                                             #

**Comment by DJEDAINI** [comment]
Added keep-files in proguard settings

**Comment by kunalkumar1993** [comment]
I have written
-keep class org.webrtc.Camera1Enumerator;
in progaurd rule but still the problem not resolve 
kindly help me in this regard

**Comment by Ejaz-Lango** [comment]
This line solved my problem. 
Add below line in the progaurd rule file.

`-keep class org.webrtc.** { *; }`

**Comment by nihar1990** [comment]
I have added the above statement in the proguard but still i am facing this issue after the signing the apk. Please help me.
