### ISSUE TITLE
QBChatDialog.setDialogId() not working!

### ISSUE THREAD

**Issue by Shahgupta0007** [QuickBlox/quickblox-android-sdk#347]
Using android SDK 3.2.0.

We trying to build 1-1 private chat feature in android app. Since user can start chatting with another user from their profile so according to the requirements we need to know whether or not QBChatDialog exists for certain recipient Id. And if it exist then how to find the dialog Id from recipient Id? In the older version, this could be achieved from QBPrivateChat.getDialogId(), do we have anything like this in current SDK since QBPrivateChat is deprecated.

 One approach is to set Dialog id in manually in code but that is not working. Even after we set dialog Id manually , quickblox seems to set the auto-generated one.
Code:  
        QBChatDialog chatDialog = DialogUtils.buildPrivateDialog(recipientId);
        chatDialog.setDialogId(dialogId);

Please help us resolve this issue..

**Comment by tatanka987** [comment]
hello @Shahgupta0007, for creating private dialog You can use next snippet:
QBChatDialog privateChatDialog = QBRestChatService.createChatDialog(
                DialogUtils.buildPrivateDialog(recipientId)).perform();

**Comment by tatanka987** [comment]
hello @Shahgupta0007, for creating private dialog you can use next snippet:
QBChatDialog privateChatDialog = QBRestChatService.createChatDialog(
DialogUtils.buildPrivateDialog(recipientId)).perform();
If private dialog was created before, you will get it, otherwise you will get new private dialog. After that you can save this dialog locally.

Or second variant - you can use next snippet to listen messages from all dialogs and init new dialogs:
//Dialogs cache
Map<String, QBChatDialog> opponentsDialogMap = ...;
 
incomingMessagesManager.addDialogMessageListener(
new QBChatDialogMessageListener() {
            @Override
            public void processMessage(String dialogId, QBChatMessage message, Integer senderId) {
            //if you don't have dialog with this dialogId just construct it:
                if (!opponnetsDialogMap.containsKey(dialogId)) {
                    QBChatDialog opponentDialog = new QBChatDialog();
                    ArrayList<Integer> occupantIds = new ArrayList<>();
                    occupantIds.add(message.getSenderId());
                    opponentDialog.setOccupantsIds(occupantIds);
 
                    //init Dialog for chatting
                    opponentDialog.initForChat(dialogId, QBDialogType.PRIVATE, chatService);
 
                    //add message listener on this Dialog
                    opponentDialog.addMessageListener(opponentDialogMsgListener);
 
                    //put Dialog in cache
                    opponnetsDialogMap.put(dialogId, opponentDialog);
                }
 
            }
 
            @Override
            public void processError(String dialogId, QBChatException exception, QBChatMessage message, Integer senderId) {
 
            }
        });

Details by link http://quickblox.com/developers/Android_XMPP_Chat_Sample#Chatting_in_dialog_SDK_3.0

**Comment by Shahgupta0007** [comment]
Thanks @tatanka987  for your quick response.

We have tried the first approach. Consider this scenario where user closes the chat screen without messaging the recipient then an empty dialog is created which should be deleted. So in this scenario we have made two REST calls(create dialog and delete dialog) for no good reason.

Your second approach seems like a good solution for us. Will try it. 

Thanks
