### ISSUE TITLE
QBDialogCustomData is not saved

### ISSUE THREAD

**Issue by ganeshub** [QuickBlox/quickblox-android-sdk#362]
setCustomData on QBDialog is not saving the custom data.

Same problem as this unanswered [SO question](http://stackoverflow.com/questions/39301088/quickblox-qbdialogcustomdata-never-submited)

**Comment by tatanka987** [comment]
hello @ganeshub on [stackoverflow](http://stackoverflow.com/questions/39301088/quickblox-qbdialogcustomdata-never-submited) author wrote problem resolved after updating QuickBlox Android SDK, if you still have any problem, please provide us logs with request and response on QuickBlox for saving QBDialogCustomData

**Comment by sgallego** [comment]
@tatanka987 I think the problem is that Android SDK is adding data[%s] format to parameters name when you put it.
If you do:
`qbDialog.getCustomData().put(SEEN1, true);`
then you get:
`qbDialog.getCustomData().getBoolean(SEEN1) == false` but
`qbDialog.getCustomData().getBoolean("data["+SEEN1+"]") == true`
so SDK is inconsistent.

**Comment by tatanka987** [comment]
@sgallego thank you for response, we will fix this issue

**Comment by alexanderkoqb** [comment]
Hey @ganeshub 
Since it's been a while and if you're still being experiencing troubles with the newer SDK (WebRTC) versions, you can contact QB here: https://assist.quickblox.com/index.php?/Base/UserRegistration/Register or raise a new issue in corresponding GitHub project.
Best!
