### ISSUE TITLE
Is there any class available like QMServiceManger (for iOS) in android sdk, which caches messages, dialogs and users

### ISSUE THREAD

**Issue by ritup22** [QuickBlox/quickblox-android-sdk#381]
*Help avoid duplicate issue reports, check [existing issues](link to issues section of repo)*

**Environment details**
*(Operating system, browser information, SDK version)*

**Did this work before?**

**Expected behavior**

**Actual behavior**

**Logs**
*(please, use github [gist](https://gist.github.com/))*

**Steps to reproduce the behavior**

**Any others comments?**

**Comment by tatanka987** [comment]
hello @ritup22 now QuickBlox Android SDK not provide this functions, but we work on this, you can see realization of cache of users in our other project Q-municate by [link ](https://github.com/QuickBlox/q-municate-android/tree/QMUN-SPRINT-2/q-municate_user_service)

**Comment by indranildutta06** [comment]
Is there any progress?

**Comment by alexanderkoqb** [comment]
Hey @ritup22 @indranildutta06
Since it's been a while and if you're still being experiencing troubles with the newer SDK (WebRTC) versions, you can contact QB here: https://assist.quickblox.com/index.php?/Base/UserRegistration/Register or raise a new issue in corresponding GitHub project.
You can visit here to check what has been done so far regarding the matter: https://quickblox.com/developers/Android_XMPP_Chat_Sample
Best!
