### ISSUE TITLE
Bluetooth connected during call not mic and speaker working.

### ISSUE THREAD

**Issue by histone** [QuickBlox/quickblox-android-sdk#426]
I have used the quickblox android sdk for calling 3.3.0.
Bluetooth not  working during call.
Steps:
Connected the Bluetooth with one phone.
Start single call audio/video.
Accept the call.
No mic or speaker (audio) not working on Bluetooth connected phone.

Can you help me to find out the way.

**Comment by RomanPronin** [comment]
QuickBlox has [test branch](https://github.com/QuickBlox/quickblox-android-sdk/tree/feature/QBANDRSDK-Bluetooth) with Bluetooth functionality.

**Comment by QB-nikolay-zolotarov** [comment]
Hello QuickBlox customers,

This is Nikolay from QuickBlox support.

The issue was closed as it is outdated.

Please check the relevant section of our documentation here:
[https://docs.quickblox.com/docs/android-video-calling](https://docs.quickblox.com/docs/android-video-calling)

Also, please update the SDK to the latest version:
[https://github.com/QuickBlox/quickblox-android-sdk-releases/releases/tag/3.9.11](https://github.com/QuickBlox/quickblox-android-sdk-releases/releases/tag/3.9.11)

Additionally, please check our new samples:
[https://docs.quickblox.com/docs/code-samples#video-calling-samples](https://docs.quickblox.com/docs/code-samples#video-calling-samples)

If it is still relevant after reviewing the updated information, feel free to open a new issue.

Have a nice day.
