### ISSUE TITLE
 quickblox videocall in background not working

### ISSUE THREAD

**Issue by sejalbaraiya** [QuickBlox/quickblox-android-sdk#438]
In this video call, web RTC is not working into without open application
If I have not opened the application then I'm not able to call 
Os how can I get on when application background

**Comment by RomanPronin** [comment]
@sejalbaraiya, in order to receive call from opponents, for ex. you can send push notification when you start call. In callee side in GcmPushListenerService by onMessageReceived() start CallService with login to chat and initQBRTCClient. So, you can receive call now. For more information look in our sample [WebRTC VideoChat](https://github.com/QuickBlox/quickblox-android-sdk/tree/master/sample-videochat-webrtc)

**Comment by RomanPronin** [comment]
Long time inactivity.
