### ISSUE TITLE
Is there any sample app for quickblox push notification n xamarin.forms

### ISSUE THREAD

**Issue by nitud** [QuickBlox/quickblox-android-sdk#446]
*Help avoid duplicate issue reports, check [existing issues](link to issues section of repo)*

**Environment details**
*(Operating system, browser information, SDK version)*

**Did this work before?**

**Expected behavior**

**Actual behavior**

**Logs**
*(please, use github [gist](https://gist.github.com/))*

**Steps to reproduce the behavior**

**Any others comments?**

**Comment by tatanka987** [comment]
sorry, but QuickBlox don't have push notification sample on Xamarin

**Comment by QB-nikolay-zolotarov** [comment]
Hello QuickBlox customer,

This is Nikolay from QuickBlox support.

The issue was closed as it is outdated.

Please update the SDK to the latest version:
[https://github.com/QuickBlox/quickblox-android-sdk-releases/releases/tag/3.9.11](https://github.com/QuickBlox/quickblox-android-sdk-releases/releases/tag/3.9.11)

If it is still relevant after reviewing the update, feel free to open a new issue.

Have a nice day.
