### ISSUE TITLE
Retrieve custom objects using user id quickblox android

### ISSUE THREAD

**Issue by githubmss** [QuickBlox/quickblox-android-sdk#449]
Please let me know how to retrieve custom object using userid in android.I have registered my license plates in custom object , Now i want to display the list of registered license plates in my application corresponding to logged in user. And able to delete any license plate from server ?

Method which i am trying

QBCustomObject customObject = new QBCustomObject();
        customObject.setClassName(Consts.CLASS_NAME);
        customObject.setUserId(Integer.parseInt(userid));

        QBCustomObjects.getObject(customObject, new QBEntityCallback<QBCustomObject>() {
            @Override
            public void onSuccess(QBCustomObject customObject, Bundle params) {

                Log.e("Latg Long"," == "+customObject.get(Consts.LicencePlate));

            }

            @Override
            public void onError(QBResponseException errors) {

            }
        });

i am using userid in place of String id in order to retrieve all related data to that user

but i am getting {"errors":["The resource wasn't found"]} , as this methods accepts String id , so is there any way by which i can found list of my license plates corresponding to USER_ID.

Any help in this.

**Comment by RomanPronin** [comment]
In QBCustomObjects.getObject(customObject, new QBEntityCallback<QBCustomObject>() customObject must contains Id of the certain customObject.
To retrieve all objects in CLASS, use QBCustomObjects.getObjects(Consts.CLASS_NAME, builder).
For more info look [here](https://quickblox.com/developers/SimpleSample-customObjects-android#With_filters).

**Comment by QB-nikolay-zolotarov** [comment]
Hello QuickBlox customer,

This is Nikolay from QuickBlox support.

The issue was closed as it is outdated.

Please check the relevant section of our documentation here:
[https://docs.quickblox.com/docs/android-custom-objects](https://docs.quickblox.com/docs/android-custom-objects)

Also, please update the SDK to the latest version:
[https://github.com/QuickBlox/quickblox-android-sdk-releases/releases/tag/3.9.11](https://github.com/QuickBlox/quickblox-android-sdk-releases/releases/tag/3.9.11)

Additionally, please check our new samples:
[https://docs.quickblox.com/docs/code-samples#chat-samples](https://docs.quickblox.com/docs/code-samples#chat-samples)

If it is still relevant after reviewing the updated information, feel free to open a new issue.

Have a nice day.
