### ISSUE TITLE
Build issue with Android Studio 3.0

### ISSUE THREAD

**Issue by HarryMMR** [QuickBlox/quickblox-android-sdk#469]
The sample code does not compile anymore after upgrading to Android Studio 3.0

**Comment by RomanPronin** [comment]
Hi @HarryMMR, have you made any changes in samples project, maybe updating gradle version? What kind of error have you got?

**Comment by HarryMMR** [comment]
No changes made. You just need to import the project into AS3.0 and try. 
Gradle is upgraded. But there are some scripts which are not compatible with AS3.0.

**Comment by RomanPronin** [comment]
So, you upgraded Gradle. Sure, there are will be some сompatibility problems in samples project. To resolve them, please, take a look at [Gradle migrate guide](https://developer.android.com/studio/build/gradle-plugin-3-0-0-migration.html).

**Comment by TugbaGonultas** [comment]
Hi @HarryMMR. Did you resolve problem? If you resolved, can you help me for same error? I tried to writes of Gradle migrate guide. But doesnt change.

**Comment by HarryMMR** [comment]
@TugbaGonultas No. Following guide doesn't help either. So for the time being, I changed back to previous AS version.

**Comment by QB-nikolay-zolotarov** [comment]
Hello QuickBlox customer,

This is Nikolay from QuickBlox support.

The issue was closed as it is outdated.

Please update the SDK to the latest version:
[https://github.com/QuickBlox/quickblox-android-sdk-releases/releases/tag/3.9.11](https://github.com/QuickBlox/quickblox-android-sdk-releases/releases/tag/3.9.11)

Additionally, please check our new samples:
[https://docs.quickblox.com/docs/code-samples#chat-samples](https://docs.quickblox.com/docs/code-samples#chat-samples)

If it is still relevant after reviewing the updated information, feel free to open a new issue.

Have a nice day.
