### ISSUE TITLE
D/QBASDK: Can't parse the 'date_sent' value null: Invalid double: "null"

### ISSUE THREAD

**Issue by naguchennai** [QuickBlox/quickblox-android-sdk#476]
Android sdk sdk-chat:3.4.1

D/QBASDK: Can't parse the 'date_sent' value null: Invalid double: "null"

if wait feve minute then send message  ... its not sent showing 
D/QBASDK: Can't parse the 'date_sent' value null: Invalid double: "null"

**Comment by RomanPronin** [comment]
@naguchennai, "Can't parse the 'date_sent' value null: Invalid double: "null" " is a debug log, and it doesn't affect to sending or receiving messages.
As for xmpp connection, it could be broken, due to bad internet connection, but it will be reestablished automatically.
If you have any other questions, please, create separate Issue. And don't write it in closed issues.

**Comment by kirtan-inexture** [comment]
@RomanPronin I am pretty sure this is causing disconnection from the xmpp client. My log files looks like this:

![image](https://user-images.githubusercontent.com/28642151/35391501-ea10cbc6-0204-11e8-947f-8206d107f8b6.png)

So, parsing "null" date is causing the `onErrorSendingPacket`.

**Comment by RomanPronin** [comment]
There may be several reasons for a disconnection, but the "Can't parse the 'date_sent'" is not one of them. Read the answer above.

**Comment by kirtan-inexture** [comment]
@RomanPronin But it is printing that log under (not below) the "Can't parse the date_sent" log.

**Comment by alexanderkoqb** [comment]
Hey @naguchennai 
Since it's been a while and if you're still being experiencing analogous troubles with the newer SDK (WebRTC) versions, you can contact QB here: https://assist.quickblox.com/index.php?/Base/UserRegistration/Register or raise a new issue in corresponding GitHub project.
Best!
