### ISSUE TITLE
How to cancel file upload 

### ISSUE THREAD

**Issue by Shahjahan786** [QuickBlox/quickblox-android-sdk#500]
How to cancel file upload : If a file is being uploaded and and due to its huge size or slow network it is taking more time to upload and user wants to cancel uploading..

**Comment by RomanPronin** [comment]
Sorry for long answer, did you try performer.cancel()? You can cancel API request after it has been started. For example:
`Performer<QBCustomObjectFileField> performer = QBCustomObjectsFiles.uploadFile(file,     qbCustomObject, fieldName);`
` performer.performAsync(new QBEntityCallback())...`

`performer.cancel();`

**Comment by Shahjahan786** [comment]
But I'm using **QBContent.uploadFileTask** method

**Comment by RomanPronin** [comment]
So, try the next:
`Performer<QBFile> performer = QBContent.uploadFileTask(file, true, null);`
`performer.performAsync(new QBEntityCallback())...`
`performer.cancel();`

**Comment by Shahjahan786** [comment]
Can I cancel file upload when progress is updated i.e 50?

**Comment by alexanderkoqb** [comment]
Whatup @Shahjahan786 
Still relevant?

**Comment by QB-nikolay-zolotarov** [comment]
Hello QuickBlox customer,

This is Nikolay from QuickBlox support.

The issue was closed as it is outdated.

Please check the relevant section of our documentation here:
[https://docs.quickblox.com/docs/android-content](https://docs.quickblox.com/docs/android-content)

Also, please update the SDK to the latest version:
[https://github.com/QuickBlox/quickblox-android-sdk-releases/releases/tag/3.9.11](https://github.com/QuickBlox/quickblox-android-sdk-releases/releases/tag/3.9.11)

Additionally, please check our new samples:
[https://docs.quickblox.com/docs/code-samples#chat-samples](https://docs.quickblox.com/docs/code-samples#chat-samples)

If it is still relevant after reviewing the updated information, feel free to open a new issue.

Have a nice day.
