### ISSUE TITLE
Audio and video call is not working when app in background in android

### ISSUE THREAD

**Issue by firojandev** [QuickBlox/quickblox-android-sdk#509]
I am using quickblox android SDK in my application.  Text chat , audio & video call working fine when application in foreground.

But audio and video call not working when app in background.

Bellow error is shown from call sender side
"E/libjingle: (turnport.cc:711): Jingle:Port[0x8df27000:audio:1:0:relay:Net[lo:127.0.0.0/8:Loopback]]: Failed to send TURN message, err=22"

How can I solve this. Please help

**Comment by RomanPronin** [comment]
Hello, @firojandev, does audio or video call work in [sample-videochat](https://github.com/QuickBlox/quickblox-android-sdk/tree/master/sample-videochat-webrtc) when app in background?

**Comment by firojandev** [comment]
Q-municate sample works for 
    - Audio with video calling
when app in background

**Comment by RomanPronin** [comment]
The error you have mentioned has nothing to do with background calls. The problem is in your implementation of video call. That's why I advised you to look carefully at the samples to find out the reason. As an assumption, you can check your push subscription, cause the CallService is started by push.

**Comment by rameshvoltella** [comment]
sample code also not working

**Comment by alexanderkoqb** [comment]
Hey @firojandev 
Has the issue been solved.

**Comment by krishnameena** [comment]
Did you find any solutions ?

**Comment by QB-nikolay-zolotarov** [comment]
Hello QuickBlox customer,

This is Nikolay from QuickBlox support.

The issue was closed as it is outdated.

Please check the relevant section of our documentation here:
[https://docs.quickblox.com/docs/android-video-calling](https://docs.quickblox.com/docs/android-video-calling)

Also, please update the SDK to the latest version:
[https://github.com/QuickBlox/quickblox-android-sdk-releases/releases/tag/3.9.11](https://github.com/QuickBlox/quickblox-android-sdk-releases/releases/tag/3.9.11)

Additionally, please check our new samples:
[https://docs.quickblox.com/docs/code-samples#video-calling-samples](https://docs.quickblox.com/docs/code-samples#video-calling-samples)

If it is still relevant after reviewing the updated information, feel free to open a new issue.

Have a nice day.
