### ISSUE TITLE
On call connection gives disconnecting-please check your internet

### ISSUE THREAD

**Issue by dhanashreee194** [QuickBlox/quickblox-android-sdk#512]
WHile calling through this app it gives Disconnecting ... please check your internet connection :+1: but the internet is working fine also permissions are set .

**Comment by RomanPronin** [comment]
This error means something wrong with chat connection and you are not logged in chat, and the reason could be the lost internet connection.

**Comment by dhanashreee194** [comment]
@RomanPronin Internet Connection is working absolutely fine.

**Comment by RomanPronin** [comment]
@dhanashreee194 Where did you get this error from? Samples, Q-mun project, etc?

**Comment by alexanderkoqb** [comment]
Hi @dhanashreee194 
Have you succeeded resolving the issue.

**Comment by QB-nikolay-zolotarov** [comment]
Hello QuickBlox customer,

This is Nikolay from QuickBlox support.

The issue was closed as it is outdated.

Please check the relevant section of our documentation here:
[https://docs.quickblox.com/docs/android-video-calling](https://docs.quickblox.com/docs/android-video-calling)

Also, please update the SDK to the latest version:
[https://github.com/QuickBlox/quickblox-android-sdk-releases/releases/tag/3.9.11](https://github.com/QuickBlox/quickblox-android-sdk-releases/releases/tag/3.9.11)

Additionally, please check our new samples:
[https://docs.quickblox.com/docs/code-samples#video-calling-samples](https://docs.quickblox.com/docs/code-samples#video-calling-samples)

If it is still relevant after reviewing the updated information, feel free to open a new issue.

Have a nice day.
