### ISSUE TITLE
Push Notifcation is not received

### ISSUE THREAD

**Issue by Narinc** [QuickBlox/quickblox-android-sdk#522]
When I first login, then put to the application to the background, it is not receiving notifications. When I kill the application completely, it starts receiving notification.

So, I cant receive notifications unless I killed the app completely.

**Comment by RomanPronin** [comment]
@Narinc, you should find out, whether you got successful subscription to pushes when make first login or not. To check subscription : Admin panel -> Push Notifications - > Subscriptions. You can check subscription for user: Admin panel -> Users - > "your" user ->In the right side below "Tags" is placed list of the subscriptions.
Also, you can send push from Admin Panel - > Push notifications - > Send. http://quickblox.com/developers/SimpleSample-messages_users-android#Send_Push_Notifications_from_Admin_panel

**Comment by QB-nikolay-zolotarov** [comment]
Hello QuickBlox customer,

This is Nikolay from QuickBlox support.

The issue was closed as it is outdated.

Please check the relevant section of our documentation here:
[https://docs.quickblox.com/docs/android-push-notifications](https://docs.quickblox.com/docs/android-push-notifications)

Also, please update the SDK to the latest version:
[https://github.com/QuickBlox/quickblox-ios-sdk/releases/tag/2.17.10](https://github.com/QuickBlox/quickblox-ios-sdk/releases/tag/2.17.10)

Additionally, please check our new samples:
[https://docs.quickblox.com/docs/code-samples#chat-samples](https://docs.quickblox.com/docs/code-samples#chat-samples)

If it is still relevant after reviewing the updated information, feel free to open a new issue.

Have a nice day.

**Comment by vikashrathore081** [comment]
implementation 'com.google.firebase:firebase-iid:21.1.0'
