### ISSUE TITLE
Localview behind the back of remoteview

### ISSUE THREAD

**Issue by A2DNEW** [QuickBlox/quickblox-android-sdk#528]
I use quickblox for call video
This is my xml :

```
<?xml version="1.0" encoding="utf-8"?>
<RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:layout_alignWithParentIfMissing="true"
    android:background="#000"
    tools:context="com.dev.trueme.VideoCallActivity">

    <com.quickblox.videochat.webrtc.view.QBRTCSurfaceView
        android:id="@+id/opponentView"
        android:layout_width="310dp"
        android:layout_height="match_parent"
        android:layout_alignParentLeft="true"
        android:layout_alignParentStart="true"
        android:layout_alignParentTop="true"
        android:layout_alignWithParentIfMissing="true" />

    <FrameLayout
        android:id="@+id/oppLayout"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:layout_alignParentRight="false"
        android:background="#33000000">

        <com.quickblox.videochat.webrtc.view.QBRTCSurfaceView
            android:id="@+id/localView"
            android:layout_width="100dp"
            android:layout_height="120dp"
            android:layout_alignParentEnd="false"
            android:layout_alignParentRight="false"
            android:layout_alignWithParentIfMissing="false" />
    </FrameLayout>
```

On receive remote video track, localview behind back opponentView and reorder automatic
Other element work correct, just localView reorder after on receive video remote

**Comment by FarisJakpau** [comment]
set localView.setZOrderMediaOverlay(true). I search for this for about 1 week. 
I hate my life.

**Comment by QB-nikolay-zolotarov** [comment]
Hello QuickBlox customer,

This is Nikolay from QuickBlox support.

The issue was closed as it was outdated.

Please check the relevant section of our documentation here:
[https://docs.quickblox.com/docs/android-video-calling](https://docs.quickblox.com/docs/android-video-calling)

Also, please update the SDK to the latest version:
[https://github.com/QuickBlox/quickblox-android-sdk-releases/releases/tag/3.9.11](https://github.com/QuickBlox/quickblox-android-sdk-releases/releases/tag/3.9.11)

Additionally, please check our new samples:
[https://docs.quickblox.com/docs/code-samples#video-calling-samples](https://docs.quickblox.com/docs/code-samples#video-calling-samples)

If it is still relevant after reviewing the updated information, feel free to open a new issue.

Have a nice day.
