### ISSUE TITLE
Is it possible to have multiple chat concurrent sessions on single device?

### ISSUE THREAD

**Issue by Shahjahan786** [QuickBlox/quickblox-android-sdk#530]
Is there any possibility to connect multiple user chat sessions at the same time so user can switch between different account like in google we can add multiple account and with between them.

**Comment by RomanPronin** [comment]
No, SDK provides one instance chatservice, so at the same time you can be logged in only with one user.

**Comment by Shahjahan786** [comment]
Is thee any way to customise[we have enterprise account] it too enable above feature?

**Comment by RomanPronin** [comment]
@Shahjahan786 At the same time on single device in chat service can be logged only one user. This behavior can't be changed. As for REST user session, of course you can manage it by yourself.

**Comment by Shahjahan786** [comment]
It means I need to logout from current chat service and create a new chat session.

**Comment by QB-nikolay-zolotarov** [comment]
Hello QuickBlox customer,

This is Nikolay from QuickBlox support.

The issue was closed as it was outdated.

Please check the relevant section of our documentation here:
[https://docs.quickblox.com/docs/android-authentication](https://docs.quickblox.com/docs/android-authentication)

Also, please update the SDK to the latest version:
[https://github.com/QuickBlox/quickblox-android-sdk-releases/releases/tag/3.9.11](https://github.com/QuickBlox/quickblox-android-sdk-releases/releases/tag/3.9.11)

Additionally, please check our new samples:
[https://docs.quickblox.com/docs/code-samples#chat-samples](https://docs.quickblox.com/docs/code-samples#chat-samples)

If it is still relevant after reviewing the updated information, feel free to open a new issue.

Have a nice day.
