### ISSUE TITLE
Can we get thumbnail url for image or video attachment?

### ISSUE THREAD

**Issue by Shahjahan786** [QuickBlox/quickblox-android-sdk#533]
Can we get thumbnail url for image or video attachment instead of actual attachment url?

**Comment by RomanPronin** [comment]
Can recommend you to create thumbnail by your own with android.media.ThumbnailUtils. And set thumbnail url in attachment as addition - attachment.setUrl("thumbnail url"); or attachment.setData("thumbnail url").

**Comment by Shahjahan786** [comment]
So I need to upload two files first to send image attachment message one for actual image and one for thumbnail. Is it possible on QB Server or it can be customised[Enterprise account] whenever I send video/image message so it automatically creates its thumbnail?

**Comment by RomanPronin** [comment]
As for customizing QB server, please contact support.

**Comment by QB-nikolay-zolotarov** [comment]
Hello QuickBlox customer,

This is Nikolay from QuickBlox support.

The issue was closed as it was outdated.

Please check the relevant section of our documentation here:
[https://docs.quickblox.com/docs/android-content](https://docs.quickblox.com/docs/android-content)

Also, please update the SDK to the latest version:
[https://github.com/QuickBlox/quickblox-android-sdk-releases/releases/tag/3.9.11](https://github.com/QuickBlox/quickblox-android-sdk-releases/releases/tag/3.9.11)

Additionally, please check our new samples:
[https://docs.quickblox.com/docs/code-samples#chat-samples](https://docs.quickblox.com/docs/code-samples#chat-samples)

If it is still relevant after reviewing the updated information, feel free to open a new issue.

Have a nice day.
