### ISSUE TITLE
Recipient ID can't be null or empty

### ISSUE THREAD

**Issue by jaikikani** [QuickBlox/quickblox-android-sdk#534]
**Environment details**
*Android Sdk Version 3.3.5*

**Expected behavior**
Message should be sent

**Actual behavior**
I face the issue when I am sending the message to the opponent user "Recipient ID can't be null or empty". This issue not reproducible because they have a different use case.

**Logs**
*https://gist.github.com/jaikikani/48b9b3152a5909cf257e5d835c3b1a0f#file-gistfile1-txt*

**Steps to reproduce the behavior**
not reproducible.

**Any others comments?**
I am facing this issue several times.

**Comment by tatanka987** [comment]
looks like you try init chatDialog in which dialogOccupants is empty or you try init chatDialog with chatServise which not logged in to the chat.

**Comment by jaikikani** [comment]
I have already logged in or chat dialog is not empty.

**Comment by tatanka987** [comment]
please check again, your user should be logged in to the chat (chatService.isLoggedIn()) and dialogIds should contains opponent's id

**Comment by ParryPatel021** [comment]
Still, I facing this issue after login into QuickBolx Chat.

**Comment by QB-nikolay-zolotarov** [comment]
Hello QuickBlox customer,

This is Nikolay from QuickBlox support.

The issue was closed as it was outdated.

Please check the relevant section of our documentation here:
[https://docs.quickblox.com/docs/android-chat-dialogs](https://docs.quickblox.com/docs/android-chat-dialogs)

Also, please update the SDK to the latest version:
[https://github.com/QuickBlox/quickblox-android-sdk-releases/releases/tag/3.9.11](https://github.com/QuickBlox/quickblox-android-sdk-releases/releases/tag/3.9.11)

Additionally, please check our new samples:
[https://docs.quickblox.com/docs/code-samples#chat-samples](https://docs.quickblox.com/docs/code-samples#chat-samples)

If it is still relevant after reviewing the updated information, feel free to open a new issue.

Have a nice day.
