### ISSUE TITLE
Notification to redirect chatactivity

### ISSUE THREAD

**Issue by bhaveshintorque** [QuickBlox/quickblox-android-sdk#539]
Anyone know  how to Redirect from push notification to particular chat Activity?

**Comment by Semafu** [comment]
bhaveshintorque,

When your push notification arrives, and the app is in the background, and you tap on the notification - does it open the app?

**Comment by bhaveshintorque** [comment]
thanks for your reply i got solution

**Comment by dailydoc7755** [comment]
> thanks for your reply I got a solution

Hello, I have been trying for 1 week now but I am not able to subscribe to push and also configure the notification with FCM. Can you help us? Also, do post your solution to the problem here so others can get help.

**Comment by QB-nikolay-zolotarov** [comment]
Hello QuickBlox customer,

This is Nikolay from QuickBlox support.

The issue was closed as it was outdated.

Please check the relevant section of our documentation here:
[https://docs.quickblox.com/docs/android-push-notifications](https://docs.quickblox.com/docs/android-push-notifications)

Also, please update the SDK to the latest version:
[https://github.com/QuickBlox/quickblox-android-sdk-releases/releases/tag/3.9.11](https://github.com/QuickBlox/quickblox-android-sdk-releases/releases/tag/3.9.11)

Additionally, please check our new samples:
[https://docs.quickblox.com/docs/code-samples#chat-samples](https://docs.quickblox.com/docs/code-samples#chat-samples)

If it is still relevant after reviewing the updated information, feel free to open a new issue.

Have a nice day.
