### ISSUE TITLE
Push Notifications when App is Closed

### ISSUE THREAD

**Issue by Semafu** [QuickBlox/quickblox-android-sdk#541]
Android, SDK 3.3.0

I receive the PUSH NOTIFICATION when the app is in foreground, and also when app is in background.

But NOT when app is closed.

However, in the log I can see that your library does get the message, but it does not call the code in the app which is called if the app is in foreground or background.

```
02-12 15:59:30.747 12552-12626/com.sem.test D/QBASDK: QBFcmPushListenerService: data: {message=DEAD}
02-12 15:59:30.747 12552-12626/com.sem.test D/QBASDK: QBFcmPushListenerService: From: 743242063XXX
02-12 15:59:30.747 12552-12626/com.sem.test D/QBASDK: QBFcmPushListenerService: Message: DEAD
```

How does it work when app closed?

Thanks.

**Comment by bhaveshintorque** [comment]
@Semafu  i also got same problem.. i m also use SDK 3.3.0, you  got any solution??

**Comment by Semafu** [comment]
:( nope.

**Comment by bhaveshintorque** [comment]
@Semafu i got solution..

**Comment by Semafu** [comment]
Give me solution..

**Comment by bhaveshintorque** [comment]
@Semafu  Do you use sample-core? then just add your Application  class into manifest

**Comment by Semafu** [comment]
It's already there. This sucks. 

Can someone from QB help. It's calling your code, but you are not passing it on.

**Comment by Semafu** [comment]
The entire point of PUSH is that you get it when the app is closed.

**Comment by schadal1** [comment]
Hi Semafu, Were you able to get a solution for this issue. ? We are facing the same issue and raised a ticket but are unable to get a solution for the same.

**Comment by prographo** [comment]
I couldn't get this to work either. QB is blackbox impossible to debug.

**Comment by schadal1** [comment]
The Push Notifications are working for some time period like 2 hours after we update the application certificate. We are mainly facing the issue in IOS. Does anybody have any idea as to why is this happening?

**Comment by tatanka987** [comment]
> We are mainly facing the issue in IOS
Please create issue for [iOS repository ](https://github.com/QuickBlox/quickblox-ios-sdk/issues)

**Comment by QB-nikolay-zolotarov** [comment]
Hello QuickBlox customer,

This is Nikolay from QuickBlox support.

The issue was closed as it was outdated.

Please check the relevant section of our documentation here:
[https://docs.quickblox.com/docs/android-push-notifications](https://docs.quickblox.com/docs/android-push-notifications)

Also, please update the SDK to the latest version:
[https://github.com/QuickBlox/quickblox-android-sdk-releases/releases/tag/3.9.11](https://github.com/QuickBlox/quickblox-android-sdk-releases/releases/tag/3.9.11)

Additionally, please check our new samples:
[https://docs.quickblox.com/docs/code-samples#chat-samples](https://docs.quickblox.com/docs/code-samples#chat-samples)

If it is still relevant after reviewing the updated information, feel free to open a new issue.

Have a nice day.
