### ISSUE TITLE
How can I get Quickblox Current User anytime anywhere in my App?

### ISSUE THREAD

**Issue by sheikhrashid** [QuickBlox/quickblox-android-sdk#546]
I need to get the **QbUser** anywhere in my app. I know the way to get the **QbUser** with several Async Methods given in Quickblox. But I need to get the **Qbuser** at once.

How can I do that?

**Comment by tatanka987** [comment]
do you need synchronously method? If yes, you can use 
```
QBUser user = QBUsers.getUser(userId).perform();
```
it will be run synchronously.

**Comment by sheikhrashid** [comment]
then how can I get userId of currentUser? anytime, anywhere in my app?

**QBSessionManager.getInstance().getSessionParameters().getUserId**

This method returning the userId null.

**Comment by sheikhrashid** [comment]
I got the userId, but it is giving me **NetworkMainThreadException** and recommends me to do asynchronously

**Comment by QB-nikolay-zolotarov** [comment]
Hello QuickBlox customer,

This is Nikolay from QuickBlox support.

The issue was closed as it was outdated.

Please update the SDK to the latest version:
[https://github.com/QuickBlox/quickblox-android-sdk-releases/releases/tag/3.9.11](https://github.com/QuickBlox/quickblox-android-sdk-releases/releases/tag/3.9.11)

Additionally, please check our new samples:
[https://docs.quickblox.com/docs/code-samples#chat-samples](https://docs.quickblox.com/docs/code-samples#chat-samples)

If it is still relevant after reviewing the updated information, feel free to open a new issue.

Have a nice day.
