### ISSUE TITLE
Migrate gcm to fcm for pushnotification

### ISSUE THREAD

**Issue by bhaveshintorque** [QuickBlox/quickblox-android-sdk#553]
While Migrate from GCM to FCM  subscription give error  "com.quickblox.core.exception.QBResponseException: Google Play services exception"

**Comment by tatanka987** [comment]
Which device do you use for test? Google Play services are actual on this device?

**Comment by bhaveshintorque** [comment]
@tatanka987  yes google services are avaliable on this device

**Comment by QB-nikolay-zolotarov** [comment]
Hello QuickBlox customer,

This is Nikolay from QuickBlox support.

The issue was closed as it was outdated.

Please check the relevant section of our documentation here:
[https://docs.quickblox.com/docs/android-push-notifications](https://docs.quickblox.com/docs/android-push-notifications)

Also, please update the SDK to the latest version:
[https://github.com/QuickBlox/quickblox-android-sdk-releases/releases/tag/3.9.11](https://github.com/QuickBlox/quickblox-android-sdk-releases/releases/tag/3.9.11)

Additionally, please check our new samples:
[https://docs.quickblox.com/docs/code-samples#chat-samples](https://docs.quickblox.com/docs/code-samples#chat-samples)

If it is still relevant after reviewing the updated information, feel free to open a new issue.

Have a nice day.
