### ISSUE TITLE
Parse x Quickblox integration issues

### ISSUE THREAD

**Issue by brunogcastro** [QuickBlox/quickblox-android-sdk#556]
I am integrating quickblox with my application in parse. After the integration, a connection bug appears and does not call the chat. Could you help me with that?

Follows the error log below:

 java.lang.IllegalStateException: ParseObject has no data for 'name'. Call fetchIfNeeded() to get the data.
02-22 20:17:33.763 26667-26667/br.com.ulearn.ulearnapp W/System.err:     at com.parse.ParseObject.checkGetAccess(ParseObject.java:3581)
02-22 20:17:33.763 26667-26667/br.com.ulearn.ulearnapp W/System.err:     at com.parse.ParseObject.getString(ParseObject.java:3175)
02-22 20:17:33.764 26667-26667/br.com.ulearn.ulearnapp W/System.err:     at br.com.ulearn.ulearnapp.view.MainActivity$3.done(MainActivity.java:120)
02-22 20:17:33.764 26667-26667/br.com.ulearn.ulearnapp W/System.err:     at br.com.ulearn.ulearnapp.view.MainActivity$3.done(MainActivity.java:101)

**Comment by brunogcastro** [comment]
https://gist.github.com/brunogcastro/10df1e33a912c7f2c15c16a9c86a6edf#file-gistfile1-txt

**Comment by RomanPronin** [comment]
We can help you if the issue is related to Quickblox code, not to Parse. So, if you have some, please post it with detailed logs and as much information as you have.

**Comment by brunogcastro** [comment]
I am not able to connect quickblox to my backend server (parse) on both Android and JS. Look at the error log below:

java.lang.IllegalStateException: ParseObject has no data for 'name'. Call fetchIfNeeded() to get the data.
02-22 20:17:33.763 26667-26667/br.com.ulearn.ulearnapp W/System.err:     at com.parse.ParseObject.checkGetAccess(ParseObject.java:3581)
02-22 20:17:33.763 26667-26667/br.com.ulearn.ulearnapp W/System.err:     at com.parse.ParseObject.getString(ParseObject.java:3175)
02-22 20:17:33.764 26667-26667/br.com.ulearn.ulearnapp W/Syst

**Comment by QB-nikolay-zolotarov** [comment]
Hello QuickBlox customer,

This is Nikolay from QuickBlox support.

The issue was closed as it was outdated.

Please check the relevant section of our documentation here:
[https://docs.quickblox.com/docs/android-authentication](https://docs.quickblox.com/docs/android-authentication)

Also, please update the SDK to the latest version:
[https://github.com/QuickBlox/quickblox-android-sdk-releases/releases/tag/3.9.11](https://github.com/QuickBlox/quickblox-android-sdk-releases/releases/tag/3.9.11)

Additionally, please check our new samples:
[https://docs.quickblox.com/docs/code-samples#chat-samples](https://docs.quickblox.com/docs/code-samples#chat-samples)

If it is still relevant after reviewing the updated information, feel free to open a new issue.

Have a nice day.
