### ISSUE TITLE
 Update QbChatMessage custom properties

### ISSUE THREAD

**Issue by RoudyK** [QuickBlox/quickblox-android-sdk#558]
**Environment details**
*(Operating system, browser information, SDK version)*
- Quickblox Android SDK - 3.7.0

**Did this work before?**
- I haven't found a working version of this

**Expected behavior**
- I would like to update QbChatMessage's custom Properties.

**Actual behavior**
- Currently the QbMessageUpdateBuilder only has the follows:
` QBMessageUpdateBuilder qbMessageUpdateBuilder = new QBMessageUpdateBuilder()
                .updateText("some text")
                .markDelivered()
                .markRead()`

Is there any workaround or hack for this currently? 
My QbChatMessage contains a custom property "PROPOSAL" which is a json representation of my custom object, this object should be updated by some event. The use of this proposal is being sent around, however there is no way to update it in a previously sent message.

**Comment by RomanPronin** [comment]
For now there is no possibility to update extra params of chatmessage. There's a possibility this feature will be added in the future releases.

**Comment by QB-nikolay-zolotarov** [comment]
Hello QuickBlox customer,

This is Nikolay from QuickBlox support.

The issue was closed as it was outdated.

Please check the relevant section of our documentation here:
[https://docs.quickblox.com/docs/android-chat-messaging#send-message-with-extra-data](https://docs.quickblox.com/docs/android-chat-messaging#send-message-with-extra-data)

Also, please update the SDK to the latest version:
[https://github.com/QuickBlox/quickblox-android-sdk-releases/releases/tag/3.9.11](https://github.com/QuickBlox/quickblox-android-sdk-releases/releases/tag/3.9.11)

If it is still relevant after reviewing the updated information, feel free to open a new issue.

Have a nice day.
