### ISSUE TITLE
QBChatDialogMessageListener is being Called 2 times

### ISSUE THREAD

**Issue by sheikhrashid** [QuickBlox/quickblox-android-sdk#562]
Hi,

I have implemented **QBChatDialogMessageListener**, but it is being called 2 times, why is it so?

Here is my Code, where I add the Listener:
`qbChatDialog.addMessageListener(messagesListener);`

And here is my Listener Code in the Class:
https://gist.github.com/sheikhrashid/0a98c38fc7819e0b853a270967d29ef2

**Comment by tatanka987** [comment]
review your code for searching multiple calling of method `addMessageListener(messagesListener)`

**Comment by sheikhrashid** [comment]
Everything is okay with the code.
What I am doing is: 

1. `QBRestChatService.getChatDialogById`
2. Then in `OnSuccess` I set the`qbChatDialog.addMessageListener(messagesListener);`

Then, when I send the message, it is being called multiple times. 

Can you help?

**Comment by tatanka987** [comment]
Did you use message listener only for separated dialog or for chatService (for listening messages from all dialogs) too? This issue related with all dialog's typeы? Please provide log which contains all steps you say about.

**Comment by sheikhrashid** [comment]
Using for separated dialogs.

**Comment by sheikhrashid** [comment]
Any Update?

**Comment by kishorejethava** [comment]
Same issue:
Kotlin code

```
 inner class ChatMessageListener : QbChatDialogMessageListenerImp() {
        override fun processMessage(s: String, qbChatMessage: QBChatMessage, integer: Int?) {
            showMessage(qbChatMessage)
        }

        override fun processError(s: String?, e: QBChatException?, qbChatMessage: QBChatMessage?, integer: Int?) {
            super.processError(s, e, qbChatMessage, integer)
            e!!.printStackTrace()
        }
    }
```

**Comment by RomanPronin** [comment]
@kishorejethava, if you receive the same message several times, then you added several instances of QBChatDialogMessageListener. Maybe one to QBIncomingMessagesManager and another to the QBChatDialog.

**Comment by QB-nikolay-zolotarov** [comment]
Hello QuickBlox customer,

This is Nikolay from QuickBlox support.

The issue was closed as it was outdated.

Please check the relevant section of our documentation here:
[https://docs.quickblox.com/docs/android-chat-dialogs](https://docs.quickblox.com/docs/android-chat-dialogs)

Also, please update the SDK to the latest version:
[https://github.com/QuickBlox/quickblox-android-sdk-releases/releases/tag/3.9.11](https://github.com/QuickBlox/quickblox-android-sdk-releases/releases/tag/3.9.11)

Additionally, please check our new samples:
[https://docs.quickblox.com/docs/code-samples#chat-samples](https://docs.quickblox.com/docs/code-samples#chat-samples)

If it is still relevant after reviewing the updated information, feel free to open a new issue.

Have a nice day.
