### ISSUE TITLE
Outdated official documentation/guides

### ISSUE THREAD

**Issue by nzkozar** [QuickBlox/quickblox-android-sdk#564]
The official implementation guide at: https://quickblox.com/developers/Sample-webrtc-android is outdated. Mostly written for version 2.6.1 with certain parts referring to other versions.

The basic setup process seems to have changed significantly enough that the above mentioned guide does not produce a working result if using newer versions of the sdk.

Is there a similar guide available made for newer (possibly the latest 3.7.0) versions of the sdk?

The github android studio project does in fact use sdk 3.7.0 but a simpler implementation guide/example would be significantly more appropriate for those trying to setup video call functionality without previous QB sdk experience. One can get lost quite easily in the complex example that is currently available on github.

**Comment by RomanPronin** [comment]
Thank you for your comment, we've made some minor changes in basic description of webrtc. But for better understanding API it is better to explore the sample.
P.S. Actually, developing new documentation is in a progress state.

**Comment by QB-nikolay-zolotarov** [comment]
Hello QuickBlox customer,

This is Nikolay from QuickBlox support.

The issue was closed as it was outdated.

Please check the relevant section of our documentation here:
[https://docs.quickblox.com/docs/android-video-calling](https://docs.quickblox.com/docs/android-video-calling)

Also, please update the SDK to the latest version:
[https://github.com/QuickBlox/quickblox-android-sdk-releases/releases/tag/3.9.11](https://github.com/QuickBlox/quickblox-android-sdk-releases/releases/tag/3.9.11)

Additionally, please check our new samples:
[https://docs.quickblox.com/docs/code-samples#video-calling-samples](https://docs.quickblox.com/docs/code-samples#video-calling-samples)

If it is still relevant after reviewing the updated information, feel free to open a new issue.

Have a nice day.
