### ISSUE TITLE
Kotlin and Quickblox?

### ISSUE THREAD

**Issue by sheikhrashid** [QuickBlox/quickblox-android-sdk#572]
I need to know is Quickblox has any documentation for **Kotlin**?

Will Quickblox work fine if I use Kotlin in Android for development.

**Comment by RomanPronin** [comment]
For now we don't have docs for Kotlin, but sure you can use Kotlin with Quickblox.

**Comment by QB-nikolay-zolotarov** [comment]
Hello QuickBlox customer,

This is Nikolay from QuickBlox support.

The issue was closed as it was outdated.

Please check the relevant section of our documentation here:
[https://docs.quickblox.com/docs/android-quick-start](https://docs.quickblox.com/docs/android-quick-start)

Also, please update the SDK to the latest version:
[https://github.com/QuickBlox/quickblox-android-sdk-releases/releases/tag/3.9.11](https://github.com/QuickBlox/quickblox-android-sdk-releases/releases/tag/3.9.11)

Additionally, please check our new samples:
[https://docs.quickblox.com/docs/code-samples#chat-samples](https://docs.quickblox.com/docs/code-samples#chat-samples)

If it is still relevant after reviewing the updated information, feel free to open a new issue.

Have a nice day.
