### ISSUE TITLE
You cannot call create unless the parent is saved 

### ISSUE THREAD

**Issue by spatil063** [QuickBlox/quickblox-android-sdk#581]

**Comment by sau05** [comment]
getting same issue

**Comment by RomanPronin** [comment]
@sau05, any chance you use login which has already been taken?

**Comment by QB-nikolay-zolotarov** [comment]
Hello QuickBlox customer,

This is Nikolay from QuickBlox support.

The issue was closed as it was outdated.

Please update the SDK to the latest version:
[https://github.com/QuickBlox/quickblox-android-sdk-releases/releases/tag/3.9.11](https://github.com/QuickBlox/quickblox-android-sdk-releases/releases/tag/3.9.11)

Additionally, please check our new samples:
[https://docs.quickblox.com/docs/code-samples#chat-samples](https://docs.quickblox.com/docs/code-samples#chat-samples)

If it is still relevant after reviewing the updated information, feel free to open a new issue.

Have a nice day.
