### ISSUE TITLE
If user is blocked can he send friend request in Roster?

### ISSUE THREAD

**Issue by Shahjahan786** [QuickBlox/quickblox-android-sdk#582]
If user is blocked can he send friend request in Roster?

**Comment by RomanPronin** [comment]
No, if user is blocked, and send friend request in Roster, hi will get "service-unavailable" error.

**Comment by QB-nikolay-zolotarov** [comment]
Hello QuickBlox customer,

This is Nikolay from QuickBlox support.

The issue was closed as it was outdated.

Please check the relevant section of our documentation here:
[https://docs.quickblox.com/docs/android-chat-privacy-list](https://docs.quickblox.com/docs/android-chat-privacy-list)

Also, please update the SDK to the latest version:
[https://github.com/QuickBlox/quickblox-android-sdk-releases/releases/tag/3.9.11](https://github.com/QuickBlox/quickblox-android-sdk-releases/releases/tag/3.9.11)

If it is still relevant after reviewing the updated information, feel free to open a new issue.

Have a nice day.
