### ISSUE TITLE
How to get Camera Instance while Video Calling is ongoing?

### ISSUE THREAD

**Issue by RIddhi8701** [QuickBlox/quickblox-android-sdk#587]
I want to turn On-Off flashlight while video calling is ongoing. For that, it needs Camera instance. I'm not able to get that from Quickblox. If I'm trying to create new Camera instance then it throws an error, "can't connect camera" because it is already in use.

**Comment by QB-nikolay-zolotarov** [comment]
Hello QuickBlox customer,

This is Nikolay from QuickBlox support.

The issue was closed as it was outdated.

Please check the relevant section of our documentation here:
[https://docs.quickblox.com/docs/android-video-calling](https://docs.quickblox.com/docs/android-video-calling)

Also, please update the SDK to the latest version:
[https://github.com/QuickBlox/quickblox-android-sdk-releases/releases/tag/3.9.11](https://github.com/QuickBlox/quickblox-android-sdk-releases/releases/tag/3.9.11)

Additionally, please check our new samples:
[https://docs.quickblox.com/docs/code-samples#video-calling-samples](https://docs.quickblox.com/docs/code-samples#video-calling-samples)

If it is still relevant after reviewing the updated information, feel free to open a new issue.

Have a nice day.
