### ISSUE TITLE
how to switch camera to rear during video call.

### ISSUE THREAD

**Issue by jamheads** [QuickBlox/quickblox-android-sdk#588]
*Help avoid duplicate issue reports, check [existing issues](link to issues section of repo)*

**Environment details**
*(Operating system, browser information, SDK version)*

**Did this work before?**

**Expected behavior**

**Actual behavior**

**Logs**
*(please, use github [gist](https://gist.github.com/))*

**Steps to reproduce the behavior**

**Any others comments?**

**Comment by QB-nikolay-zolotarov** [comment]
Hello QuickBlox customer,

This is Nikolay from QuickBlox support.

The issue was closed as it was outdated.

Please check the relevant section of our documentation here:
[https://docs.quickblox.com/docs/android-video-calling-advanced#switch-camera](https://docs.quickblox.com/docs/android-video-calling-advanced#switch-camera)

Also, please update the SDK to the latest version:
[https://github.com/QuickBlox/quickblox-android-sdk-releases/releases/tag/3.9.11](https://github.com/QuickBlox/quickblox-android-sdk-releases/releases/tag/3.9.11)

Additionally, please check our new samples:
[https://docs.quickblox.com/docs/code-samples#video-calling-samples](https://docs.quickblox.com/docs/code-samples#video-calling-samples)

If it is still relevant after reviewing the updated information, feel free to open a new issue.

Have a nice day.
