### ISSUE TITLE
Option for making group dialog admins

### ISSUE THREAD

**Issue by Shahjahan786** [QuickBlox/quickblox-android-sdk#589]
Currently there is no option for making group admins. will you add this feature?

**Comment by sahil-mobi** [comment]
did this feature get added?

**Comment by Ahmadpashaquarterpi** [comment]
Any Updates About Changing the Group Owner?

**Comment by QB-nikolay-zolotarov** [comment]
Hello QuickBlox customer,

This is Nikolay from QuickBlox support.

The issue was closed as it was outdated.

Please check the relevant section of our documentation here:
[https://docs.quickblox.com/docs/android-chat-dialogs#create-dialog](https://docs.quickblox.com/docs/android-chat-dialogs#create-dialog)

Also, please update the SDK to the latest version:
[https://github.com/QuickBlox/quickblox-android-sdk-releases/releases/tag/3.9.11](https://github.com/QuickBlox/quickblox-android-sdk-releases/releases/tag/3.9.11)

Additionally, please check our new samples:
[https://docs.quickblox.com/docs/code-samples#chat-samples](https://docs.quickblox.com/docs/code-samples#chat-samples)

If it is still relevant after reviewing the updated information, feel free to open a new issue.

Have a nice day.
