### ISSUE TITLE
Attachment image gets rotate captured by Samsung camera

### ISSUE THREAD

**Issue by RIddhi8701** [QuickBlox/quickblox-android-sdk#592]
When I'm sending a message with attachment image from Samsung camera.
If you see uploaded image in Quickblox admin panel -> Content folder,  the image is rotated
In iPhone device, it looks perfect while showing chat history
In android also looks perfect
but in Web, it seems rotated.

Thank you!

**Comment by RomanPronin** [comment]
Hello @RIddhi8701. Yeah, indeed, it is a specific device issue. Maybe you can find a solution here https://github.com/google/cameraview/issues/22

**Comment by QB-nikolay-zolotarov** [comment]
Hello QuickBlox customer,

This is Nikolay from QuickBlox support.

The issue was closed as it was outdated.

Please check the relevant section of our documentation here:
[https://docs.quickblox.com/docs/android-content](https://docs.quickblox.com/docs/android-content)

Also, please update the SDK to the latest version:
[https://github.com/QuickBlox/quickblox-android-sdk-releases/releases/tag/3.9.11](https://github.com/QuickBlox/quickblox-android-sdk-releases/releases/tag/3.9.11)

Additionally, please check our new samples:
[https://docs.quickblox.com/docs/code-samples#chat-samples](https://docs.quickblox.com/docs/code-samples#chat-samples)

If it is still relevant after reviewing the updated information, feel free to open a new issue.

Have a nice day.
