### ISSUE TITLE
Is QuickBlox can do face detection when video call?

### ISSUE THREAD

**Issue by LemonNicholas** [QuickBlox/quickblox-android-sdk#595]
May i know QuickBlox can do face detection when video call or can i get camera object inside quickblox sdk?

**Comment by RomanPronin** [comment]
Hi @LemonNicholas. When video call is started, the camera is captured by webrtc and not accessible. But maybe the next methods will help you. So, you can release camera with method:
``` 
((QBRTCCameraVideoCapturer)(currentSession.getMediaStreamManager().getVideoCapturer())).stopCapture();
```

use Face detection, and then startCapture again:
```
((QBRTCCameraVideoCapturer)(currentSession.getMediaStreamManager().getVideoCapturer())). startCapture(width, height, framerate);
```

**Comment by QB-nikolay-zolotarov** [comment]
Hello QuickBlox customer,

This is Nikolay from QuickBlox support.

The issue was closed as it was outdated.

Please check the relevant section of our documentation here:
[https://docs.quickblox.com/docs/android-video-calling](https://docs.quickblox.com/docs/android-video-calling)

Also, please update the SDK to the latest version:
[https://github.com/QuickBlox/quickblox-android-sdk-releases/releases/tag/3.9.11](https://github.com/QuickBlox/quickblox-android-sdk-releases/releases/tag/3.9.11)

Additionally, please check our new samples:
[https://docs.quickblox.com/docs/code-samples#video-calling-samples](https://docs.quickblox.com/docs/code-samples#video-calling-samples)

If it is still relevant after reviewing the updated information, feel free to open a new issue.

Have a nice day.
