### ISSUE TITLE
Entity you are looking for was not found.,The resource wasn't found      I got this Exception while delete message in android quickblox

### ISSUE THREAD

**Issue by tatveshwebmigrates** [QuickBlox/quickblox-android-sdk#603]
how to solve this error Entity you are looking for was not found.,The resource wasn't found???

**Comment by ParryPatel021** [comment]
I also facing this error while creating a new dialog OR fetch the existing dialog.

**Comment by QB-nikolay-zolotarov** [comment]
Hello QuickBlox customer,

This is Nikolay from QuickBlox support.

The issue was closed as it was outdated.

Please update the SDK to the latest version:
[https://github.com/QuickBlox/quickblox-android-sdk-releases/releases/tag/3.9.11](https://github.com/QuickBlox/quickblox-android-sdk-releases/releases/tag/3.9.11)

Additionally, please check our new samples:
[https://docs.quickblox.com/docs/code-samples#chat-samples](https://docs.quickblox.com/docs/code-samples#chat-samples)

If it is still relevant after reviewing the updated information, feel free to open a new issue.

Have a nice day.
