### ISSUE TITLE
QBResponseException: You have already logged in chat.

### ISSUE THREAD

**Issue by williamtran1988** [QuickBlox/quickblox-android-sdk#605]
Hi All,

I am using : QBChatService.getInstance().isLoggedIn to check if user has already logged in chat. But it did not work sometimes. Because i received an error exception by calling login api:

QBChatService.getInstance().login it throws an exception like : "You have already logged in chat"

Could you please tell me how can we handle this case?

BR,
William Tran.

**Comment by haris15** [comment]
any update on it
or
do you find any solution

**Comment by HiteshDevganiya** [comment]
Any update here ?

**Comment by freshindee** [comment]
Any update here ?

**Comment by QuickBlox-team** [comment]
This email is confirmation that you are now registered at our helpdesk.

Registered email: reply@reply.github.com
Password: 8dm9pmd7vu

You can visit the helpdesk to browse articles and contact us at any time: https://assist.quickblox.com/

Thank you for registering!


QuickBlox

Helpdesk: https://assist.quickblox.com/index.php?

**Comment by QB-nikolay-zolotarov** [comment]
Hello QuickBlox customer,

This is Nikolay from QuickBlox support.

The issue was closed as it was outdated.

Please check the relevant section of our documentation here:
[https://docs.quickblox.com/docs/android-authentication](https://docs.quickblox.com/docs/android-authentication)

Also, please update the SDK to the latest version:
[https://github.com/QuickBlox/quickblox-android-sdk-releases/releases/tag/3.9.11](https://github.com/QuickBlox/quickblox-android-sdk-releases/releases/tag/3.9.11)

Additionally, please check our new samples:
[https://docs.quickblox.com/docs/code-samples#chat-samples](https://docs.quickblox.com/docs/code-samples#chat-samples)

If it is still relevant after reviewing the updated information, feel free to open a new issue.

Have a nice day.
