### ISSUE TITLE
QuickBLox Notification not receving

### ISSUE THREAD

**Issue by vineeshtp** [QuickBlox/quickblox-android-sdk#611]
I have developed an application it was working fine before some days.
I already raised in stackoverflow.
[https://stackoverflow.com/questions/51219767/didreceiveincomingpushwith-not-working-ios](url)

Now I noticed that, By using the quickBlox admin panel itself I am not receiving the VOIP notifications
But, it shows that it is sent

<img width="1042" alt="screen shot 2018-07-07 at 12 02 22 pm" src="https://user-images.githubusercontent.com/2011379/42407668-26db752a-81de-11e8-87d7-9865051f4ac6.png">

**Logs**
Here is the message Log,
[Message Log ](https://gist.github.com/vineeshtp/99e0c14c4ed8921c35ad875d5cf1111f)

**Steps to reproduce the behavior**

**Any others comments?**

**Comment by vineeshtp** [comment]
Please any updates?

**Comment by rizwanjillani** [comment]
Please tell if any updates related to notifications ?

**Comment by QB-nikolay-zolotarov** [comment]
Hello QuickBlox customer,

This is Nikolay from QuickBlox support.

The issue was closed as it was outdated.

Please check the relevant section of our documentation here:
[https://docs.quickblox.com/docs/ios-push-notifications](https://docs.quickblox.com/docs/ios-push-notifications)

Also, please update the SDK to the latest version:
[https://github.com/QuickBlox/quickblox-ios-sdk/releases/tag/2.17.10](https://github.com/QuickBlox/quickblox-ios-sdk/releases/tag/2.17.10)

Additionally, please check our new samples:
[https://docs.quickblox.com/docs/code-samples#chat-samples](https://docs.quickblox.com/docs/code-samples#chat-samples)

If it is still relevant after reviewing the updated information, feel free to open a new issue in the iOS repository.

Have a nice day.
