### ISSUE TITLE
Differents versions Glide

### ISSUE THREAD

**Issue by javieritis** [QuickBlox/quickblox-android-sdk#613]
I use the glide version 

    implementation 'com.github.bumptech.glide:glide:4.7.1'
    annotationProcessor 'com.github.bumptech.glide:compiler:4.7.1'

and QuickBlox 

    implementation 'com.quickblox:quickblox-android-sdk-chat:3.7.0'
    implementation 'com.quickblox:quickblox-android-sdk-core:3.7.0'
    implementation 'com.quickblox:quickblox-android-sdk-messages:3.7.0'

When i use the chat adapter (QBMessagesAdapter), return me exception and crash.:

`    java.lang.NoSuchMethodError: No static method clear(Landroid/view/View;)V in class Lcom/bumptech/glide/Glide; or its super classes (declaration of 'com.bumptech.glide.Glide' appears in /data/app/com.apptest.dev-1/base.apk)
`

Is there any way for Quickblox to use your Glide version and I use the one I have in my project?

I have seen that it uses version 3.6.1 of Glide in Quickblox.
https://github.com/QuickBlox/quickblox-android-sdk/blob/master/build.gradle

thanks!

**Comment by Shakir4u** [comment]
Not yet Dear. I am getting same issue.

**Comment by QB-nikolay-zolotarov** [comment]
Hello QuickBlox customer,

This is Nikolay from QuickBlox support.

The issue was closed as it was outdated.

Please update the SDK to the latest version:
[https://github.com/QuickBlox/quickblox-android-sdk-releases/releases/tag/3.9.11](https://github.com/QuickBlox/quickblox-android-sdk-releases/releases/tag/3.9.11)

Additionally, please check our new samples:
[https://docs.quickblox.com/docs/code-samples#chat-samples](https://docs.quickblox.com/docs/code-samples#chat-samples)

If it is still relevant after reviewing the updated information, feel free to open a new issue.

Have a nice day.
