### ISSUE TITLE
Not getting call(Audio/Video) from android to iPhone when app is in background and vice versa. 

### ISSUE THREAD

**Issue by brijeshwebmigrates** [QuickBlox/quickblox-android-sdk#615]
I am doing call from Android phone to iPhone but not getting call when iPhone app is in background. It is working fine when app is in foreground. 

       try {
            QBPushNotifications.createEvent(pushEvent).perform();
            Log.e("pusheventsuccess", "success");
        } catch (QBResponseException e) {
            Log.e("pusheventsuccess", "fail"+e.toString());
        }

Actually when i call and if iPhone app is in background then every time it is giving me this error in catch block.
    
 **Error => quickblox.core.exception.QBResponseException: No one can receive the message**

This is also same for iPhone to android. When iPhone app is calling to android user and if app is in background then i am not getting any notification or event. 

Can you please suggest me how can i solve this.

**Comment by krishnameena** [comment]
Did you find any solutions ?

**Comment by QB-nikolay-zolotarov** [comment]
Hello QuickBlox customer,

This is Nikolay from QuickBlox support.

The issue was closed as it was outdated.

Please check the relevant section of our documentation here:
[https://docs.quickblox.com/docs/android-video-calling](https://docs.quickblox.com/docs/android-video-calling)

Also, please update the SDK to the latest version:
[https://github.com/QuickBlox/quickblox-android-sdk-releases/releases/tag/3.9.11](https://github.com/QuickBlox/quickblox-android-sdk-releases/releases/tag/3.9.11)

Additionally, please check our new samples:
[https://docs.quickblox.com/docs/code-samples#video-calling-samples](https://docs.quickblox.com/docs/code-samples#video-calling-samples)

If it is still relevant after reviewing the updated information, feel free to open a new issue.

Have a nice day.
