### ISSUE TITLE
Freind List And Name from Contacts Like Whatsapp

### ISSUE THREAD

**Issue by Bosa17** [QuickBlox/quickblox-android-sdk#620]
Hello,
I want to have whatsapp like feature in my app. i Want to get the friend name and list from phone contacts and added to a users freind table as the new user signs up. I want them to add them automatically to their contact's New Message Activity , available to start a private Dialog.

Please Reply Soon.

**Comment by hachich46** [comment]
@Bosa17,

You can get something like this in this video : https://www.youtube.com/watch?v=qFaoOfpd97c

Hope you are helped.

**Comment by QB-nikolay-zolotarov** [comment]
Hello QuickBlox customer,

This is Nikolay from QuickBlox support.

The issue was closed as it was outdated.

Please check the relevant section of our documentation here:
[https://docs.quickblox.com/docs/android-chat-contact-list](https://docs.quickblox.com/docs/android-chat-contact-list)

Also, please update the SDK to the latest version:
[https://github.com/QuickBlox/quickblox-android-sdk-releases/releases/tag/3.9.11](https://github.com/QuickBlox/quickblox-android-sdk-releases/releases/tag/3.9.11)

Additionally, please check our new samples:
[https://docs.quickblox.com/docs/code-samples#chat-samples](https://docs.quickblox.com/docs/code-samples#chat-samples)

If it is still relevant after reviewing the updated information, feel free to open a new issue.

Have a nice day.
