### ISSUE TITLE
How To Record Audio Video Call Using Quickblox in Android?

### ISSUE THREAD

**Issue by vasupujy** [QuickBlox/quickblox-android-sdk#621]
I  ma trying to this link but can't it https://quickblox.com/developers/Sample-webrtc-android if anyone did it then please help me

**Comment by hoang-pham-virtium** [comment]
any idea? Please share it with me. I really need this.

**Comment by phamhoangbl** [comment]
any idea about this? I really need this, please!

**Comment by QB-nikolay-zolotarov** [comment]
Hello QuickBlox customer,

This is Nikolay from QuickBlox support.

The issue was closed as it was outdated.

The feature of recording audio/video calls is available only for conference calls.
Conference audio/video calls functionality is provided as an addon for all paid plans.
You may read more here:
[https://quickblox.com/pricing/](https://quickblox.com/pricing/)
In order to use the video conference calling feature, you need to purchase a dedicated Janus server.

Server side recording functionality can be enabled/disabled for the entire server from our side. Every call will be recorded if the feature is enabled.

Audio and video files are recorded for each user separately and stored on the server.

If you are interested in audio/video conference functionality and call recording, feel free to [contact our Sales team](https://quickblox.com/enterprise/#get-enterprise) to get more information.

If there are any further questions, please open a new issue. We will be happy to help you.
