### ISSUE TITLE
Crash on QBGroupChat.sendMessage (class not in use within our app)

### ISSUE THREAD

**Issue by fr4gus** [QuickBlox/quickblox-android-sdk#626]
*Help avoid duplicate issue reports, check [existing issues](link to issues section of repo)*

**Environment details**
*(Operating system, browser information, SDK version)*
Android SDK 26 (26.0.2 Build tools)

**Did this work before?**
n/a

**Expected behavior**
Deprecated class not used not used in the App but apparently in the QB SDK provoke crashes.

**Actual behavior**
Crash on method call of class QBGroupChat that is not in used within our app

**Logs**
*(please, use github [gist](https://gist.github.com/))*

com.quickblox.chat.QBGroupChat.sendMessage (Unknown Source:11)
--
  | com.quickblox.chat.QBAbstractChat$a.performInAsync (Unknown Source:4)
  | com.quickblox.chat.utils.ThreadTaskEx.run (Unknown Source)
  | java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1167)
  | java.lang.Thread.run (Thread.java:764)

**Steps to reproduce the behavior**
We have sporadic reports in Crashlytics. I repeat, we don't use this class, so we don't know why the app is crashing. The documentation says it's deprecated so we suspect this one is used within the SDK unintentionally provoking crashes.

**Any others comments?**

**Comment by QB-nikolay-zolotarov** [comment]
Hello QuickBlox customer,

This is Nikolay from QuickBlox support.

The issue was closed as it was outdated.

Please check the relevant section of our documentation here:
[https://docs.quickblox.com/docs/android-chat-dialogs](https://docs.quickblox.com/docs/android-chat-dialogs)

Also, please update the SDK to the latest version:
[https://github.com/QuickBlox/quickblox-android-sdk-releases/releases/tag/3.9.11](https://github.com/QuickBlox/quickblox-android-sdk-releases/releases/tag/3.9.11)

Additionally, please check our new samples:
[https://docs.quickblox.com/docs/code-samples#chat-samples](https://docs.quickblox.com/docs/code-samples#chat-samples)

If it is still relevant after reviewing the updated information, feel free to open a new issue.

Have a nice day.
