### ISSUE TITLE
QBResponseException: base Unexpected signature

### ISSUE THREAD

**Issue by haris15** [QuickBlox/quickblox-android-sdk#628]
please help me to solve this

09-04 14:50:00.676 2762-2762/com.miream.miream W/System.err: com.quickblox.core.exception.QBResponseException: base Unexpected signature
09-04 14:50:00.676 2762-2762/com.miream.miream W/System.err:     at com.quickblox.core.parser.QBJsonParser.parse(Unknown Source)
09-04 14:50:00.677 2762-2762/com.miream.miream W/System.err:     at com.quickblox.auth.session.Query$VersionEntityCallback.completedWithResponse(Unknown Source)
09-04 14:50:00.677 2762-2762/com.miream.miream W/System.err:     at com.quickblox.auth.session.Query.completedWithResponse(Unknown Source)
09-04 14:50:00.677 2762-2762/com.miream.miream W/System.err:     at com.quickblox.core.server.HttpRequestRunnable$1.handleMessage(Unknown Source)
09-04 14:50:00.677 2762-2762/com.miream.miream W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:102)
09-04 14:50:00.677 2762-2762/com.miream.miream W/System.err:     at android.os.Looper.loop(Looper.java:163)
09-04 14:50:00.677 2762-2762/com.miream.miream W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:6239)
09-04 14:50:00.677 2762-2762/com.miream.miream W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
09-04 14:50:00.677 2762-2762/com.miream.miream W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
09-04 14:50:00.677 2762-2762/com.miream.miream W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:794)

**Comment by QB-nikolay-zolotarov** [comment]
Hello QuickBlox customer,

This is Nikolay from QuickBlox support.

The issue was closed as it was outdated.

Please check the relevant section of our documentation here:
[https://docs.quickblox.com/docs/android-authentication](https://docs.quickblox.com/docs/android-authentication)

Please make sure that you generate a signature correctly according to our documentation:
https://docs.quickblox.com/reference/authentication#section-signature-generation

Also, please update the SDK to the latest version:
[https://github.com/QuickBlox/quickblox-android-sdk-releases/releases/tag/3.9.11](https://github.com/QuickBlox/quickblox-android-sdk-releases/releases/tag/3.9.11)

Additionally, please check our new samples:
[https://docs.quickblox.com/docs/code-samples#chat-samples](https://docs.quickblox.com/docs/code-samples#chat-samples)

If it is still relevant after reviewing the updated information, feel free to open a new issue.

Have a nice day.
