### ISSUE TITLE
Client is not, or no longer, connected.

### ISSUE THREAD

**Issue by HFMohammad** [QuickBlox/quickblox-android-sdk#629]
Hi

My code:

```
final QBChatDialog dialog = DialogUtils.buildPrivateDialog(id);
        dialog.setType(QBDialogType.PRIVATE);

        QBRestChatService.createChatDialog(dialog).performAsync(new QBEntityCallback<QBChatDialog>() {
            @Override
            public void onSuccess(QBChatDialog result, Bundle params) {
                try {
                    QBChatMessage chatMessage = new QBChatMessage();
                    chatMessage.setBody("Hi there!");
                    dialog.sendMessage(chatMessage);
                } catch (SmackException.NotConnectedException e) {
                    Log.i("errorCheck", "Chat: NO : " + e.getMessage());
                }
            }

            @Override
            public void onError(QBResponseException responseException) {
                Log.i("errorCheck", "Chat: FAIL" + responseException.getMessage());
            }
        });
```

I get this error :

    Client is not, or no longer, connected. error

**Comment by HFMohammad** [comment]
Can help me ?

**Comment by KundanIws** [comment]
Yes we are still facing this issue

**Comment by QB-nikolay-zolotarov** [comment]
Hello QuickBlox customer,

This is Nikolay from QuickBlox support.

The issue was closed as it was outdated.

Please check the relevant section of our documentation here:
[https://docs.quickblox.com/docs/android-chat-dialogs#create-dialog](https://docs.quickblox.com/docs/android-chat-dialogs#create-dialog)

Also, please update the SDK to the latest version:
[https://github.com/QuickBlox/quickblox-android-sdk-releases/releases/tag/3.9.11](https://github.com/QuickBlox/quickblox-android-sdk-releases/releases/tag/3.9.11)

Additionally, please check our new samples:
[https://docs.quickblox.com/docs/code-samples#chat-samples](https://docs.quickblox.com/docs/code-samples#chat-samples)

If it is still relevant after reviewing the updated information, feel free to open a new issue.

Have a nice day.
