### ISSUE TITLE
Mark all messages not Working.QBRestChatService.markMessagesAsRead() onsuccess called but sender not get any callback

### ISSUE THREAD

**Issue by imvikasrai** [QuickBlox/quickblox-android-sdk#633]
QBRestChatService.markMessagesAsRead(dialogId, null).performAsync(new QBEntityCallback<Void>() {
                @Override
                public void onSuccess(Void aVoid, Bundle bundle) {
                    Log.e(TAG, "onSuccess:markMessagesAsRead " );
                }

                @Override
                public void onError(QBResponseException e) {
                    Log.e(TAG, "onError:markMessagesAsRead ex"+e.getMessage() );
                }
            });

**Comment by QB-nikolay-zolotarov** [comment]
Hello QuickBlox customer,

This is Nikolay from QuickBlox support.

The issue was closed as it was outdated.

Please check the relevant section of our documentation here:
[https://docs.quickblox.com/docs/android-chat-messaging#mark-message-as-read](https://docs.quickblox.com/docs/android-chat-messaging#mark-message-as-read)

Also, please update the SDK to the latest version:
[https://github.com/QuickBlox/quickblox-android-sdk-releases/releases/tag/3.9.11](https://github.com/QuickBlox/quickblox-android-sdk-releases/releases/tag/3.9.11)

Additionally, please check our new samples:
[https://docs.quickblox.com/docs/code-samples#chat-samples](https://docs.quickblox.com/docs/code-samples#chat-samples)

If it is still relevant after reviewing the updated information, feel free to open a new issue.

Have a nice day.
