### ISSUE TITLE
Android: quickblox android 8 version incoming message not work

### ISSUE THREAD

**Issue by HFMohammad** [QuickBlox/quickblox-android-sdk#641]
I use below code:

```
incomingMessage = QBChatService.getInstance().getIncomingMessagesManager();
incomingMessage.addDialogMessageListener(new QBChatDialogMessageListener() {
    @Override
    public void processMessage(String s, final QBChatMessage qbChatMessage, Integer id) {
        if (id > 0) {
            QBRestChatService.getChatDialogById(qbChatMessage.getDialogId()).performAsync(new QBEntityCallback<QBChatDialog>() {
                @Override
                public void onSuccess(QBChatDialog qbChatDialog, Bundle bundle) {
                    // OK
                }

                @Override
                public void onError(QBResponseException e) {
                    // ERROR
                }
            });
        }
    }

    @Override
    public void processError(String s, QBChatException e, QBChatMessage qbChatMessage, Integer integer) {
        // ERROR
    }
});
```

In all versions of andorid work fine.

But for android 8.0 not work correct. sometimes get messages and sometimes not get messages!

How can i fix it ?

**Comment by grovervikas** [comment]
I am also having the same issue, it might be issue with Doze mode. In Doze mode Android OS doesn't allow to run background service and hence chat connection dropped and won't be receive push notification. I am also struggling with the same issue. Have you found the solution ?

**Comment by QuickBlox-team** [comment]
This email is confirmation that you are now registered at our helpdesk.

Registered email: reply@reply.github.com
Password: zykxuctot7

You can visit the helpdesk to browse articles and contact us at any time: https://assist.quickblox.com/

Thank you for registering!


QuickBlox

Helpdesk: https://assist.quickblox.com/index.php?

**Comment by QB-nikolay-zolotarov** [comment]
Hello QuickBlox customer,

This is Nikolay from QuickBlox support.

The issue was closed as it was outdated.

Please check the relevant section of our documentation here:
[https://docs.quickblox.com/docs/android-chat-messaging](https://docs.quickblox.com/docs/android-chat-messaging)

Also, please update the SDK to the latest version:
[https://github.com/QuickBlox/quickblox-android-sdk-releases/releases/tag/3.9.11](https://github.com/QuickBlox/quickblox-android-sdk-releases/releases/tag/3.9.11)

Additionally, please check our new samples:
[https://docs.quickblox.com/docs/code-samples#chat-samples](https://docs.quickblox.com/docs/code-samples#chat-samples)

If it is still relevant after reviewing the updated information, feel free to open a new issue.

Have a nice day.
