### ISSUE TITLE
While Updated android studio 2.3 to 3.1.4 getting various errors in Quick blox.

### ISSUE THREAD

**Issue by kiranNanda** [QuickBlox/quickblox-android-sdk#643]
Gradle sync Failed:
1) Unable to resolve dependency for ':app@debug/compileClasspath': Could not resolve project :sample-videochat-webrtc.
2) Unable to resolve dependency for ':app@debugAndroidTest/compileClasspath': Could not resolve project :sample-videochat-webrtc.
3) Unable to resolve dependency for ':app@debugUnitTest/compileClasspath': Could not resolve project :sample-videochat-webrtc.
4) Unable to resolve dependency for ':app@release/compileClasspath': Could not resolve project :sample-videochat-webrtc.
5) Unable to resolve dependency for ':app@releaseUnitTest/compileClasspath': Could not resolve project :sample-videochat-webrtc.
Can u help to resolve this issues while Gradle is :classpath 'com.android.tools.build:gradle:3.1.2'
  classpath 'com.google.gms:google-services:4.1.0' 
distributionUrl=https\://services.gradle.org/distributions/gradle-4.4-all.zip
and google play services : 9.8.0 
and other     androidLibsVersion = '16.0.0'

**Comment by iwebservicesrepo** [comment]
I am still facing this issue.

**Comment by QB-nikolay-zolotarov** [comment]
Hello QuickBlox customer,

This is Nikolay from QuickBlox support.

The issue was closed as it was outdated.

Please update the SDK to the latest version:
[https://github.com/QuickBlox/quickblox-android-sdk-releases/releases/tag/3.9.11](https://github.com/QuickBlox/quickblox-android-sdk-releases/releases/tag/3.9.11)

Additionally, please check our new samples:
[https://docs.quickblox.com/docs/code-samples#chat-samples](https://docs.quickblox.com/docs/code-samples#chat-samples)

If it is still relevant after reviewing the updated information, feel free to open a new issue.

Have a nice day.
