### ISSUE TITLE
In call adding

### ISSUE THREAD

**Issue by whytepurvesh** [QuickBlox/quickblox-android-sdk#650]
I want to add a person in the group video call during an ongoing call, is there any way to achieve this through quickblox ?

**Comment by QB-nikolay-zolotarov** [comment]
Hello QuickBlox customer,

This is Nikolay from QuickBlox support.

The issue was closed as it was outdated.

We would like to inform you that all participants of an audio\video call should be indicated initially (before the establishment of a connection between users) so there is no way to implement the functionality to join an ongoing audio/video call.
This is an option to reconnect/rejoin participants in case they were disconnected for some reason during the audio/video call.

If you have any other questions, please open a new issue.
