### ISSUE TITLE
Cache for Dialogs like iOS

### ISSUE THREAD

**Issue by imran-samed** [QuickBlox/quickblox-android-sdk#651]
Is there any class available in Android SDK for cache of dialog chats??
I'm using **3.9.0** SDK in my project.  !!

**Comment by imran-samed** [comment]
@tatanka987  plz reply ASAP, its really needed.

**Comment by QB-nikolay-zolotarov** [comment]
Hello QuickBlox customer,

This is Nikolay from QuickBlox support.

The issue was closed as it was outdated.

Please check the relevant section of our documentation here:
[https://docs.quickblox.com/docs/android-chat-dialogs#create-dialog](https://docs.quickblox.com/docs/android-chat-dialogs#create-dialog)

Also, please update the SDK to the latest version:
[https://github.com/QuickBlox/quickblox-android-sdk-releases/releases/tag/3.9.11](https://github.com/QuickBlox/quickblox-android-sdk-releases/releases/tag/3.9.11)

Additionally, please check our new samples:
[https://docs.quickblox.com/docs/code-samples#chat-samples](https://docs.quickblox.com/docs/code-samples#chat-samples)

If it is still relevant after reviewing the updated information, feel free to open a new issue.

Have a nice day.
