### ISSUE TITLE
Push notification to iOs from Admin panel

### ISSUE THREAD

**Issue by imcodervn** [QuickBlox/quickblox-android-sdk#652]
I use tool push notification for all subscription that subscribe to Quickblox use iOs platform.
I added certificate for push but when I use Quickblox tool to push for production environment, my client don't receive notification and my client's subscription is removed on subscription list

**Comment by QB-nikolay-zolotarov** [comment]
Hello QuickBlox customer,

This is Nikolay from QuickBlox support.

The issue was closed as it was outdated.

Please check the relevant section of our documentation here:
[https://docs.quickblox.com/docs/ios-push-notifications](https://docs.quickblox.com/docs/ios-push-notifications)

Also, please update the SDK to the latest version:
[https://github.com/QuickBlox/quickblox-ios-sdk/releases/tag/2.17.10](https://github.com/QuickBlox/quickblox-ios-sdk/releases/tag/2.17.10)

Additionally, please check our new samples:
[https://docs.quickblox.com/docs/code-samples#chat-samples](https://docs.quickblox.com/docs/code-samples#chat-samples)

If it is still relevant after reviewing the updated information, feel free to open a new issue in the iOS repository.

Have a nice day.
