### ISSUE TITLE
Quickblox Android 3.9.0 :  java.lang.NoClassDefFoundError: Failed resolution of: Landroidx/core/app/JobIntentService;

### ISSUE THREAD

**Issue by jatin-lakhani** [QuickBlox/quickblox-android-sdk#656]
*Help avoid duplicate issue reports, check [existing issues](link to issues section of repo)*

**Environment details**
*(Operating system, browser information, SDK version)*

**Did this work before?**

**Expected behavior**

**Actual behavior**

**Logs**
*(please, use github [gist](https://gist.github.com/))*

**Steps to reproduce the behavior**

**Any others comments?**

**Comment by jatin-lakhani** [comment]
I've just updated my Quickblox libraries and I got to crash on the below line.

QBSettings.getInstance().init(getApplicationContext(), qbConfigs.getAppId(), qbConfigs.getAuthKey(), qbConfigs.getAuthSecret());


Crash Logs:
java.lang.NoClassDefFoundError: Failed resolution of: Landroidx/core/app/JobIntentService;
        at com.quickblox.messages.QBPushNotifications.<clinit>(Unknown Source:4)
        at java.lang.Class.classForName(Native Method)
        at java.lang.Class.forName(Class.java:453)
        at com.quickblox.auth.session.QBClassInitializer.initClass(Unknown Source:7)
        at com.quickblox.auth.session.QBSettings.getInstance(Unknown Source:16)

**Comment by QB-nikolay-zolotarov** [comment]
Hello QuickBlox customer,

This is Nikolay from QuickBlox support.

The issue was closed as it was outdated.

Please update the SDK to the latest version:
[https://github.com/QuickBlox/quickblox-android-sdk-releases/releases/tag/3.9.11](https://github.com/QuickBlox/quickblox-android-sdk-releases/releases/tag/3.9.11)

Additionally, please check our new samples:
[https://docs.quickblox.com/docs/code-samples#chat-samples](https://docs.quickblox.com/docs/code-samples#chat-samples)

If it is still relevant after reviewing the updated information, feel free to open a new issue.

Have a nice day.
