### ISSUE TITLE
Unauthorised error while Signup

### ISSUE THREAD

**Issue by imran-samed** [QuickBlox/quickblox-android-sdk#658]
**SDK 3.9.0**

**Did this work before?**
it occur some time and get reslove automatically after couple of hrs

**Expected behavior**
Signup could never be unauthorised

**Actual behavior**
Signup is unauthorised

**Logs**
please check the log below
https://gist.github.com/imran-samed/88c86656a92f2b983f6bdb6b8ca7234b  

**Steps to reproduce the behavior**
Just signup with new user its will give unauthorised error but few times not all time.

**Comment by tempersitu** [comment]
Same problem. I found the problem is that I had logout B user and then login A user, but when I set a breakpoint on QBUsers.signIn(A user), the quickblox log shows B user's parameter. I'm sure that the parameter is A user.

SDK 3.8.1
**Did this work before?**
it occur some time and get reslove automatically after couple of hrs

And I found that it goes back normal if I clean app's cache.

**Comment by tempersitu** [comment]
It's strange that there's no matter about neither A user nor B user. Some time SDK try to login quickblox by a a/c which id is 1073(always 1073). However, there's no a/c which id is 1073 in our DB or Quickblox user at all. 

`PARAMETERS
        application_id=xxxxx
        auth_key=LWREKcjBQykNFWG
        nonce=1513127846
        timestamp=1551435034
        user[email]=xxxxxx_1073@xxxxx.com.hk
        user[login]=xxxxxx_1073
        user[password]=782dfc10a645020ae5638b7d82019c50
        signature=84ec15549f002340fb44e88368b7822c125d3c47
    INLINE
        POST https://api.quickblox.com/session.json?application_id=xxxxx&auth_key=LWREKcjBQykNFWG&nonce=1513127846&timestamp=1551435034&user[email]=xxxxxx_1073%40xxxxx.com.hk&user[login]=xxxxxx_1073&user[password]=782dfc10a645020ae5638b7d82019c50&signature=84ec15549f002340fb44e88368b7822c125d3c47`

**Comment by QB-nikolay-zolotarov** [comment]
Hello QuickBlox customer,

This is Nikolay from QuickBlox support.

The issue was closed as it was outdated.

Please check the relevant section of our documentation here:
[https://docs.quickblox.com/docs/android-authentication](https://docs.quickblox.com/docs/android-authentication)

Also, please update the SDK to the latest version:
[https://github.com/QuickBlox/quickblox-android-sdk-releases/releases/tag/3.9.11](https://github.com/QuickBlox/quickblox-android-sdk-releases/releases/tag/3.9.11)

Additionally, please check our new samples:
[https://docs.quickblox.com/docs/code-samples#chat-samples](https://docs.quickblox.com/docs/code-samples#chat-samples)

If it is still relevant after reviewing the updated information, feel free to open a new issue.

Have a nice day.
