### ISSUE TITLE
Issue with create subscription push notification in Android SDK

### ISSUE THREAD

**Issue by thanhduy26091995** [QuickBlox/quickblox-android-sdk#662]
I'm working with quickblox push notification. I have an issue like this
In Quickblox's document, I see an instruction about create subscription 
https://quickblox.com/developers/Messages#Create_subscription_.28subscribes.29
This API contains a parameter like this **_push_token[bundle_identifier]_**
But in the Android SDK, it does not have any parameter like this. So when I create a subscription using Android SDK.
The bundle_id I saw in ****dashboard**  -> push notification -> Subscriptions -> detail subscription** is blank
![image](https://user-images.githubusercontent.com/18645098/55876142-1c1d2a80-5bc1-11e9-9144-b0579aaf4c2e.png)

So I think that's a reason why I can not receive any message from tab **Queue**. 
Please help me resolver this.
Thanks a lot

**Comment by QB-nikolay-zolotarov** [comment]
Hello QuickBlox customer,

This is Nikolay from QuickBlox support.

The issue was closed as it was outdated.

Please check the relevant section of our documentation here:
[https://docs.quickblox.com/docs/android-push-notifications](https://docs.quickblox.com/docs/android-push-notifications)

Also, please update the SDK to the latest version:
[https://github.com/QuickBlox/quickblox-android-sdk-releases/releases/tag/3.9.11](https://github.com/QuickBlox/quickblox-android-sdk-releases/releases/tag/3.9.11)

Additionally, please check our new samples:
[https://docs.quickblox.com/docs/code-samples#chat-samples](https://docs.quickblox.com/docs/code-samples#chat-samples)

If it is still relevant after reviewing the updated information, feel free to open a new issue.

Have a nice day.
