### ISSUE TITLE
Unable to see my own Video track

### ISSUE THREAD

**Issue by ajaychoudhary491** [QuickBlox/quickblox-android-sdk#663]
I'm not able to see my own video track but I can see opponents video .Any help?

"onRemoteAudioTrackReceive" is calling properly but "onLocalVideoTrackReceive" not being called

**Comment by QuickBlox-team** [comment]
This email is confirmation that you are now registered at our helpdesk.

Registered email: reply@reply.github.com
Password: t4es2l8rx3

You can visit the helpdesk to browse articles and contact us at any time: https://assist.quickblox.com/

Thank you for registering!


QuickBlox

Helpdesk: https://assist.quickblox.com/index.php?

**Comment by FarisJakpau** [comment]
Hi @ajaychoudhary491, I also had the same problem as you. In my situation, this is actually my phone problem. My phone suddenly restarted and all my application need to reaccess the system permission again like camera, contact, and others. 
So you can try to reaccess the permission in your app. Maybe it helps.

**Comment by QB-nikolay-zolotarov** [comment]
Hello QuickBlox customer,

This is Nikolay from QuickBlox support.

The issue was closed as it was outdated.

Please check the relevant section of our documentation here:
[https://docs.quickblox.com/docs/android-video-calling](https://docs.quickblox.com/docs/android-video-calling)

Also, please update the SDK to the latest version:
[https://github.com/QuickBlox/quickblox-android-sdk-releases/releases/tag/3.9.11](https://github.com/QuickBlox/quickblox-android-sdk-releases/releases/tag/3.9.11)

Additionally, please check our new samples:
[https://docs.quickblox.com/docs/code-samples#video-calling-samples](https://docs.quickblox.com/docs/code-samples#video-calling-samples)

If it is still relevant after reviewing the updated information, feel free to open a new issue.

Have a nice day.
