### ISSUE TITLE
Show Avatar In Chat Adapter for Android and iOS

### ISSUE THREAD

**Issue by impalawebspooja** [QuickBlox/quickblox-android-sdk#669]
I am trying to load user's avatar image inside Chat Adapter. In newer quickblox chat version there is a method with name obtainAvatarUrl which returns null value. Please provide the accurate way to show user's profile image in chat adapter.

qbSdkVersion = '3.9.1'

**Comment by impalawebspooja** [comment]
Please help me to get the user's profile image and name in public chat.

**Comment by alexparvus1** [comment]
To load User's avatar you should find avatarID (fileID) in model QBUser and load QBFile by this ID. Then you can load image by URL or load file directly into the storage: 
```
                String fullName = qbUser.getFullName();
                Integer avatarID = qbUser.getFileId();

                QBContent.getFile(avatarID).performAsync(new QBEntityCallback<QBFile>() {
                    @Override
                    public void onSuccess(QBFile qbFile, Bundle bundle) {
                        String avatarURL = qbFile.getPrivateUrl();
                        // Use avatar URL to load image
                    }

                    @Override
                    public void onError(QBResponseException e) {
                        e.printStackTrace();
                    }
                });
```

**Comment by QB-nikolay-zolotarov** [comment]
Hello QuickBlox customer,

This is Nikolay from QuickBlox support.

The issue was closed as it was outdated.

Please check the relevant section of our documentation here:
[https://docs.quickblox.com/docs/flutter-users#set-user-avatar](https://docs.quickblox.com/docs/flutter-users#set-user-avatar)

Also, please update the SDK to the latest version:
[https://github.com/QuickBlox/quickblox-android-sdk-releases/releases/tag/3.9.11](https://github.com/QuickBlox/quickblox-android-sdk-releases/releases/tag/3.9.11)

Additionally, please check our new samples:
[https://docs.quickblox.com/docs/code-samples#chat-samples](https://docs.quickblox.com/docs/code-samples#chat-samples)

If it is still relevant after reviewing the updated information, feel free to open a new issue.

Have a nice day.
