### ISSUE TITLE
Get the user's profile image and name in public chat.

### ISSUE THREAD

**Issue by impalawebspooja** [QuickBlox/quickblox-android-sdk#670]
Please help me to get the user's profile image and name in public chat. The public room has no occupants then how can I get this information?

**Comment by impalawebspooja** [comment]
anyone who knows the solution of this problem?

**Comment by QB-nikolay-zolotarov** [comment]
Hello QuickBlox customer,

This is Nikolay from QuickBlox support.

The issue was closed as it was outdated.

Please check the relevant section of our documentation here:
[https://docs.quickblox.com/docs/flutter-users#set-user-avatar](https://docs.quickblox.com/docs/flutter-users#set-user-avatar)

Also, please update the SDK to the latest version:
[https://github.com/QuickBlox/quickblox-android-sdk-releases/releases/tag/3.9.11](https://github.com/QuickBlox/quickblox-android-sdk-releases/releases/tag/3.9.11)

If it is still relevant after reviewing the updated information, feel free to open a new issue.

Have a nice day.
