### ISSUE TITLE
Notification Push 

### ISSUE THREAD

**Issue by rpinto18** [QuickBlox/quickblox-android-sdk#672]
Hello, Is push notification possible from user to user? 

Example?

Thanks.

**Comment by alexparvus1** [comment]
Late is better than never :)
To send Push to other QB-User you should create QBEvent.
For example like this:

```
QBEvent qbEvent = new QBEvent();
qbEvent.setNotificationType(QBNotificationType.PUSH);
qbEvent.setEnvironment(QBEnvironment.DEVELOPMENT);
qbEvent.setMessage(outMessage); // All text you need to send

StringifyArrayList<Integer> userIds = new StringifyArrayList<>();
userIds.add(opponentId());

qbEvent.setUserIds(userIds);

QBPushNotifications.createEvent(qbEvent).performAsync(new QBEntityCallback<QBEvent>() {
@Override
public void onSuccess(QBEvent qbEvent, Bundle bundle) {
// Successful created QBEvent
}

@Override
public void onError(QBResponseException e) {
// Error with creating QBEvent
}
```

All what you need to know to send Pushes with Quickblox SDK - there: https://docs.quickblox.com/docs/android-push-notifications

**Comment by QB-nikolay-zolotarov** [comment]
Hello QuickBlox customer,

This is Nikolay from QuickBlox support.

The issue was closed as it was outdated.

Please check the relevant section of our documentation here:
[https://docs.quickblox.com/docs/android-push-notifications](https://docs.quickblox.com/docs/android-push-notifications)

Also, please update the SDK to the latest version:
[https://github.com/QuickBlox/quickblox-android-sdk-releases/releases/tag/3.9.11](https://github.com/QuickBlox/quickblox-android-sdk-releases/releases/tag/3.9.11)

Additionally, please check our new samples:
[https://docs.quickblox.com/docs/code-samples#chat-samples](https://docs.quickblox.com/docs/code-samples#chat-samples)

If it is still relevant after reviewing the updated information, feel free to open a new issue.

Have a nice day.
