### ISSUE TITLE
Continue Video/Voice Call Session

### ISSUE THREAD

**Issue by FarisJakpau** [QuickBlox/quickblox-android-sdk#675]
Hi All, 

Currently, I am implementing voice and video call from quickblox SDK. So im having a issue that  im not be able to continue the call when the apps being killed. The QBRTClient session return null when i reentered my app. 
How do i get the session back from the save session or the session always being killed when the apps killed?

Thank You.

**Comment by alexparvus1** [comment]
Late is better than never :)
How to hold your call even when your application was killed by operation system you can find there - https://github.com/QuickBlox/quickblox-android-sdk/blob/master/sample-videochat-java/app/src/main/java/com/quickblox/sample/videochat/java/services/CallService.java

As you can see - you should use Service to hold and process the call.

**Comment by pumatus** [comment]
CallService Will not execute in the background。Why~

**Comment by QB-nikolay-zolotarov** [comment]
Hello QuickBlox customer,

This is Nikolay from QuickBlox support.

The issue was closed as it was outdated.

Please check the relevant section of our documentation here:
[https://docs.quickblox.com/docs/android-video-calling](https://docs.quickblox.com/docs/android-video-calling)

Also, please update the SDK to the latest version:
[https://github.com/QuickBlox/quickblox-android-sdk-releases/releases/tag/3.9.11](https://github.com/QuickBlox/quickblox-android-sdk-releases/releases/tag/3.9.11)

Additionally, please check our new samples:
[https://docs.quickblox.com/docs/code-samples#video-calling-samples](https://docs.quickblox.com/docs/code-samples#video-calling-samples)

If it is still relevant after reviewing the updated information, feel free to open a new issue.

Have a nice day.
