### ISSUE TITLE
How to make video calls in NativeScript with QuickBlox

### ISSUE THREAD

**Issue by Izrab** [QuickBlox/quickblox-android-sdk#677]
It has been days since I am struggling to get an answer to this question, I posted on Stack Overflow, I tried to call QuickBlox phone numbers, I posted a thread on QuickBlox tickets, and I got no responses, **no responses at all**. Then I opened issue in this repository. Lets not even talk about how bad and little and scarce are the documentations. 

Now, can I make video calls with QuickBlox in NativeScript apps? If yes, how? What are the steps? If no, why?

**Comment by QB-nikolay-zolotarov** [comment]
Hello QuickBlox customer,

This is Nikolay from QuickBlox support.

The issue was closed as it was outdated.

Please check the relevant section of our documentation here:
[https://docs.quickblox.com/docs/android-video-calling](https://docs.quickblox.com/docs/android-video-calling)

Also, please update the SDK to the latest version:
[https://github.com/QuickBlox/quickblox-android-sdk-releases/releases/tag/3.9.11](https://github.com/QuickBlox/quickblox-android-sdk-releases/releases/tag/3.9.11)

Additionally, please check our new samples:
[https://docs.quickblox.com/docs/code-samples#video-calling-samples](https://docs.quickblox.com/docs/code-samples#video-calling-samples)

If it is still relevant after reviewing the updated information, feel free to open a new issue.

Have a nice day.
