### ISSUE TITLE
QBRestChatservice not working

### ISSUE THREAD

**Issue by shakilahmeda** [QuickBlox/quickblox-android-sdk#681]
QBRestChatservice not working in android studio java . 
why not working QBRestChatservice and how can i solve this

**Comment by alexparvus1** [comment]
Unfortunately, we have nothing to do with this problem, especially if you won't give us little bit more information.

**Comment by QB-nikolay-zolotarov** [comment]
Hello QuickBlox customer,

This is Nikolay from QuickBlox support.

The issue was closed as it was outdated.

Pease update the SDK to the latest version:
[https://github.com/QuickBlox/quickblox-android-sdk-releases/releases/tag/3.9.11](https://github.com/QuickBlox/quickblox-android-sdk-releases/releases/tag/3.9.11)

Additionally, please check our new samples:
[https://docs.quickblox.com/docs/code-samples#chat-samples](https://docs.quickblox.com/docs/code-samples#chat-samples)

If it is still relevant after reviewing the updated information, feel free to open a new issue.

Have a nice day.
