### ISSUE TITLE
How to record video call?

### ISSUE THREAD

**Issue by devDecepticon** [QuickBlox/quickblox-android-sdk#682]
is there any way to record a video call?? I have checked the closed issue #257
, Nothing is providing any clearer information about how to achieve it. There should be YES or NO with some reasoning. So is there any way to achieve the video call record and if Yes then please show us a way to do it?

**Comment by QB-nikolay-zolotarov** [comment]
Hello QuickBlox customer,

This is Nikolay from QuickBlox support.

The issue was closed as it was outdated.

Hello {{case.requester.first_name}},

Thank you for contacting QuickBlox support!

The feature of recording audio/video calls is available only for conference calls.
Conference audio/video calls functionality is provided as an addon for all paid plans.
You may read more here:
[https://quickblox.com/pricing/](https://quickblox.com/pricing/)
In order to use the video conference calling feature, you need to purchase a dedicated Janus server.

Server side recording functionality can be enabled/disabled for the entire server from our side. Every call will be recorded if the feature is enabled.

Audio and video files are recorded for each user separately and stored on the server.

If you are interested in audio/video conference functionality and call recording, feel free to [contact our Sales team ](https://quickblox.com/enterprise/#get-enterprise) to get more information.

If there are any further questions, feel free to open a new issue.
