### ISSUE TITLE
setScalingType does not work

### ISSUE THREAD

**Issue by Esvux** [QuickBlox/quickblox-android-sdk#688]
**Environment details**
* Android (Minimal API 19, targetSDK 28)
* Quickblox Android SDK 3.9.1 (Java)

**Description**
When my app receives a new remote video track (the app only works with peer-to-peer video calls), the video is rendered correctly but not display according to the scaling type. 

```java
    @Override
    public void onRemoteVideoTrackReceive(QBRTCSession session, final QBRTCVideoTrack videoTrack, final Integer userID) {
        Log.d(TAG, "onRemoteVideoTrackReceive for opponent= " + userID);

        if (localVideoTrack != null) {
            fillVideoView(localVideoView, localVideoTrack, false);
        }
        isLocalVideoFullScreen = false;
        setDuringCallActionBar();
        fillVideoView(userID, remoteFullScreenVideoView, videoTrack, true);
        updateVideoView(remoteFullScreenVideoView, false);
    }
```

**Expected behavior**
I expect that calling the method setScalingType with *SCALE_ASPECT_FIT* as argument the video should be adjust automatically, putting horizontal or vertical black bars.
`surfaceViewRenderer.setScalingType(RendererCommon.ScalingType.SCALE_ASPECT_FIT);`

**Actual behavior**
The video is not adjusted automatically.

**Any others comments?**
Actually, I adjust the size manually using margins, but it's depends for the remote video aspect ratio. This works fine if the aspect-ratio is 4:3. Extra question, is there a way to know the aspect ratio or the resolution of remote video source?

**Comment by alexparvus1** [comment]
As I checked - Scaling Type works fine.

If something works wrong you can compare the logic with the sample - https://github.com/QuickBlox/quickblox-android-sdk/tree/master/sample-videochat-java

There are three scaling types for QBSurfaceView:

ScalingType scalingType;
scalingType = RendererCommon.ScalingType.SCALE_ASPECT_FIT;
scalingType = RendererCommon.ScalingType.SCALE_ASPECT_FILL;
scalingType = RendererCommon.ScalingType.SCALE_ASPECT_BALANCED;

surfaceViewRenderer.setScalingType(scalingType);

**Comment by QB-nikolay-zolotarov** [comment]
Hello QuickBlox customer,

This is Nikolay from QuickBlox support.

The issue was closed as it was outdated.

Please check the relevant section of our documentation here:
[https://docs.quickblox.com/docs/android-video-calling](https://docs.quickblox.com/docs/android-video-calling)

Also, please update the SDK to the latest version:
[https://github.com/QuickBlox/quickblox-android-sdk-releases/releases/tag/3.9.11](https://github.com/QuickBlox/quickblox-android-sdk-releases/releases/tag/3.9.11)

Additionally, please check our new samples:
[https://docs.quickblox.com/docs/code-samples#video-calling-samples](https://docs.quickblox.com/docs/code-samples#video-calling-samples)

If it is still relevant after reviewing the updated information, feel free to open a new issue.

Have a nice day.
