### ISSUE TITLE
NO users to call

### ISSUE THREAD

**Issue by veronikawilliams1** [QuickBlox/quickblox-android-sdk#730]
Hello,
I logged in app "sample videochat" and saw 

> **"Logged in as <my name>, select users you want to call".**

 But there is empty list !!! No users. 

What I'm doing wrong? Please, help! : )

**Comment by veronikawilliams1** [comment]
Please, I want any solution

**Comment by veronikawilliams1** [comment]
Any ideas /

**Comment by veronikawilliams1** [comment]
did you manage to make a call?

**Comment by QB-maksym-pidhorbunskyi** [comment]
Hello Veronika,

Thank you for contacting QuickBlox support.

In order to make video calls and use a QuickBlox video calling sample, please make sure that you have a QuickBlox account.
You can create an account here: https://admin.quickblox.com/signup 

The step-by-step instructions on how to create a new QuickBlox account and an application could be found here: https://quickblox.com/developers/5_Minute_Guide 

Please check QuickBlox documentation on how to use QuickBlox Android video calling sample: https://docs.quickblox.com/docs/android-quick-start#video-chat-sample 

You need to make sure that there are users created within your application.

In order to create users, please follow the next instructions:
1. Log into your QuickBlox account
2. Go to applications by clicking on Applications button and select your application.
3. Select Users tab from the left sidebar menu.
4. Click Add New User button and create a new user.

If you have any questions, please let me know.

Best regards, 
Maksym Pidhorbunskyi,
Customer Support Representative

**Comment by veronikawilliams1** [comment]
**THANK YOU SO MUCH MAX**! EVERYTHING WORKED!
I don't know what I would do without you :) U're my hero

**Comment by QB-maksym-pidhorbunskyi** [comment]
Hello Veronika,

Glad to hear that the issue is resolved :)
