### ISSUE TITLE
Message send issue if use same device for two different login

### ISSUE THREAD

**Issue by sagarbhojaviya** [QuickBlox/quickblox-android-sdk#783]
**Environment details**
*Using Android OS
SDK version 3.9.13*

**Did this work before?**
*No*

**Expected behavior**
*I am using demo example of chat in kotlin*
*Check attached video for reference*

**Issue**
*In video i am doing login using **testc** user after i send message to **testsagar** user it is working fine. But if i logout from **testc** user and do login using **testsagar** user i am receiving message of **testc** user and sending message to **testc** it is not sending to **testc*** actual issue happed here. Message sending by **testc** every time if i login as **testsagar**

Please check this issue and give me response or suggestion ASAP.

Thanks.

**Video Reference**

*Video (1) for **testc** user login*
https://user-images.githubusercontent.com/53989478/159653485-f1867ca9-edbf-49b1-9f74-dc6e7f4aea55.mp4

*Video (2,3 and 4) for **testsagar** user login*
https://user-images.githubusercontent.com/53989478/159663937-6b2cdbc3-8e25-48da-aeaf-b5bf83f0fbbf.mp4
https://user-images.githubusercontent.com/53989478/159664177-f7ee1ff9-5730-44e3-baaa-f52a8d8a9811.mp4
https://user-images.githubusercontent.com/53989478/159664307-37c1e3d0-8459-4d00-b71e-d106a819b11f.mp4

**Comment by QB-nikolay-zolotarov** [comment]
Hello @sagarbhojaviya 

This is Nikolay from QuickBlox support.

To investigate the issue further please provide the following points:
1. Please try using the latest version of the SDK:
https://github.com/QuickBlox/quickblox-android-sdk-releases/releases/tag/3.9.15
2. Is this issue intermittent or permanent?
3. Please provide us with full REST + XMPP logs from the application start till the wrong behavior as an attachment in .txt format. 
You can find out how to gather logs here: https://help.quickblox.com/article/368-how-can-i-enable-quickblox-logs
4. Versions of Android platform where reproduces the issue (e.g. Android 9).
5. Phone models (e.g. Samsung S9). Please specify if the issue is somehow related to a specific device and Android versions.
