### ISSUE TITLE
DateTime issue in getting message server time.

### ISSUE THREAD

**Issue by MihirPal** [QuickBlox/quickblox-android-sdk#79]
Whatever message we are getting from private chat are coming in form of **QBChatMessage**.
for getting message time we have **date_sent** tag to get timemiles. But this tag is not giving server message time. This is the time send by user who send that perticular message. 

But in iOS sdk they provide **datetime** which is providing message server time which is unique.

So basically what happen, iOS app will user message server time and Android app will use time send by sender of the message or device own date and time. 

I have check https://github.com/QuickBlox/q-municate-android also in which iOS and android differens in terms of Timings.

Do we missed anything here?

**Comment by MihirPal** [comment]
Do we have any plan to make it availabe in android version?

**Comment by soulfly** [comment]
A field 'datetime' for iOS is equal to datetime when message arrived to the device ( new Date() for Android ), so it's also not the server side datetime

Chat server also uses 'date_sent' when it saves messages to data base. But there is a validation logic.
Chat server validates this value (check a difference between client's and server's timestamps - it should not be more than 5 seconds). If a difference is less then 5 seconds - server will use client's value, otherwise - ignore client's value and use own.

**Comment by MihirPal** [comment]
Okay so you wanna say, We will have datetime which is send by us. 
In case my device is having wrong datetime set, so it will set date_sent accordingly. So we will have difference over there right?

There is no way to have server syncronized time?

**Comment by rahulparikh** [comment]
@MihirPal  did you found any solution ?

@soulfly  can you please guide us how can we get time of server ? it will be appreciable if you help to get server time. or give some reference link..

**Comment by ruchiragile** [comment]
@soulfly , please reply !!

**Comment by Dandroas** [comment]
Any idea when we might get a response on this?

**Comment by soulfly** [comment]
You can use this to get server time

https://github.com/QuickBlox/android-ntp-time-utils

this is how it works
https://github.com/QuickBlox/android-ntp-time-utils/blob/master/app/src/main/java/com/quickblox/ntptimeutils/MainActivity.java#L21
