### ISSUE TITLE
How to assign admin ownership to the second participant in the group

### ISSUE THREAD

**Issue by Kumar-Evoke-Github** [QuickBlox/quickblox-android-sdk#798]
Is it possible to change the dialog owner to other group participants? when does he leave the dialog?

Example: I created a dialog with three participants (1,2.3), I created with 1...after creation 1 left from the dialog. then is it possible to assign dialog ownership to the second participant?

Currently, we are using Quickblox Android and iOS SDKs...We need to main current admin of Dialog... Please help me with this...

**Comment by kkvarma9387** [comment]
I received the below email from Quickblox

We apologize for the misunderstanding.
Only the group owner can add/remove occupants while other occupants can only add other users.
You can find more information about dialog rules here: https://docs.quickblox.com/reference/update-dialog

We will edit our documentation in order to avoid such misunderstanding.
If you would like us to implement such a possibility, please consider using our custom development service.

Please let us know if you have other questions.
